// flow-typed signature: 00a01ad43703a49fed08f78c1fae206d
// flow-typed version: <<STUB>>/async-mqtt_v^1.0.1/flow_v0.77.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'async-mqtt'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'async-mqtt' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'async-mqtt/test' {
  declare module.exports: any;
}

// Filename aliases
declare module 'async-mqtt/index' {
  declare module.exports: $Exports<'async-mqtt'>;
}
declare module 'async-mqtt/index.js' {
  declare module.exports: $Exports<'async-mqtt'>;
}
declare module 'async-mqtt/test.js' {
  declare module.exports: $Exports<'async-mqtt/test'>;
}
