// flow-typed signature: 24366fd1f2c9240282db8febf7c944ab
// flow-typed version: <<STUB>>/aws-amplify-react_v^0.1.38/flow_v0.76.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'aws-amplify-react'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'aws-amplify-react' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'aws-amplify-react/dist/AmplifyI18n' {
  declare module.exports: any;
}

declare module 'aws-amplify-react/dist/AmplifyMessageMap' {
  declare module.exports: any;
}

declare module 'aws-amplify-react/dist/AmplifyTheme' {
  declare module.exports: any;
}

declare module 'aws-amplify-react/dist/AmplifyUI' {
  declare module.exports: any;
}

declare module 'aws-amplify-react/dist/Analytics/index' {
  declare module.exports: any;
}

declare module 'aws-amplify-react/dist/Analytics/trackLifecycle' {
  declare module.exports: any;
}

declare module 'aws-amplify-react/dist/Analytics/trackUpdate' {
  declare module.exports: any;
}

declare module 'aws-amplify-react/dist/API/GraphQL/Connect' {
  declare module.exports: any;
}

declare module 'aws-amplify-react/dist/API/GraphQL/index' {
  declare module.exports: any;
}

declare module 'aws-amplify-react/dist/API/index' {
  declare module.exports: any;
}

declare module 'aws-amplify-react/dist/Auth/Authenticator' {
  declare module.exports: any;
}

declare module 'aws-amplify-react/dist/Auth/AuthPiece' {
  declare module.exports: any;
}

declare module 'aws-amplify-react/dist/Auth/AuthStateWrapper' {
  declare module.exports: any;
}

declare module 'aws-amplify-react/dist/Auth/ConfirmSignIn' {
  declare module.exports: any;
}

declare module 'aws-amplify-react/dist/Auth/ConfirmSignUp' {
  declare module.exports: any;
}

declare module 'aws-amplify-react/dist/Auth/FederatedSignIn' {
  declare module.exports: any;
}

declare module 'aws-amplify-react/dist/Auth/ForgotPassword' {
  declare module.exports: any;
}

declare module 'aws-amplify-react/dist/Auth/Greetings' {
  declare module.exports: any;
}

declare module 'aws-amplify-react/dist/Auth/index' {
  declare module.exports: any;
}

declare module 'aws-amplify-react/dist/Auth/Provider/index' {
  declare module.exports: any;
}

declare module 'aws-amplify-react/dist/Auth/Provider/withAmazon' {
  declare module.exports: any;
}

declare module 'aws-amplify-react/dist/Auth/Provider/withFacebook' {
  declare module.exports: any;
}

declare module 'aws-amplify-react/dist/Auth/Provider/withGoogle' {
  declare module.exports: any;
}

declare module 'aws-amplify-react/dist/Auth/Provider/withOAuth' {
  declare module.exports: any;
}

declare module 'aws-amplify-react/dist/Auth/RequireNewPassword' {
  declare module.exports: any;
}

declare module 'aws-amplify-react/dist/Auth/SignIn' {
  declare module.exports: any;
}

declare module 'aws-amplify-react/dist/Auth/SignUp' {
  declare module.exports: any;
}

declare module 'aws-amplify-react/dist/Auth/TOTPSetup' {
  declare module.exports: any;
}

declare module 'aws-amplify-react/dist/Auth/VerifyContact' {
  declare module.exports: any;
}

declare module 'aws-amplify-react/dist/index' {
  declare module.exports: any;
}

declare module 'aws-amplify-react/dist/Storage/Common' {
  declare module.exports: any;
}

declare module 'aws-amplify-react/dist/Storage/index' {
  declare module.exports: any;
}

declare module 'aws-amplify-react/dist/Storage/S3Album' {
  declare module.exports: any;
}

declare module 'aws-amplify-react/dist/Storage/S3Image' {
  declare module.exports: any;
}

declare module 'aws-amplify-react/dist/Storage/S3Text' {
  declare module.exports: any;
}

declare module 'aws-amplify-react/dist/Widget/index' {
  declare module.exports: any;
}

declare module 'aws-amplify-react/dist/Widget/PhotoPicker' {
  declare module.exports: any;
}

declare module 'aws-amplify-react/dist/Widget/Picker' {
  declare module.exports: any;
}

declare module 'aws-amplify-react/dist/Widget/SelectMFAType' {
  declare module.exports: any;
}

declare module 'aws-amplify-react/dist/Widget/TextPicker' {
  declare module.exports: any;
}

declare module 'aws-amplify-react/dist/Widget/TOTPSetupComp' {
  declare module.exports: any;
}

// Filename aliases
declare module 'aws-amplify-react/dist/AmplifyI18n.js' {
  declare module.exports: $Exports<'aws-amplify-react/dist/AmplifyI18n'>;
}
declare module 'aws-amplify-react/dist/AmplifyMessageMap.js' {
  declare module.exports: $Exports<'aws-amplify-react/dist/AmplifyMessageMap'>;
}
declare module 'aws-amplify-react/dist/AmplifyTheme.js' {
  declare module.exports: $Exports<'aws-amplify-react/dist/AmplifyTheme'>;
}
declare module 'aws-amplify-react/dist/AmplifyUI.js' {
  declare module.exports: $Exports<'aws-amplify-react/dist/AmplifyUI'>;
}
declare module 'aws-amplify-react/dist/Analytics/index.js' {
  declare module.exports: $Exports<'aws-amplify-react/dist/Analytics/index'>;
}
declare module 'aws-amplify-react/dist/Analytics/trackLifecycle.js' {
  declare module.exports: $Exports<'aws-amplify-react/dist/Analytics/trackLifecycle'>;
}
declare module 'aws-amplify-react/dist/Analytics/trackUpdate.js' {
  declare module.exports: $Exports<'aws-amplify-react/dist/Analytics/trackUpdate'>;
}
declare module 'aws-amplify-react/dist/API/GraphQL/Connect.js' {
  declare module.exports: $Exports<'aws-amplify-react/dist/API/GraphQL/Connect'>;
}
declare module 'aws-amplify-react/dist/API/GraphQL/index.js' {
  declare module.exports: $Exports<'aws-amplify-react/dist/API/GraphQL/index'>;
}
declare module 'aws-amplify-react/dist/API/index.js' {
  declare module.exports: $Exports<'aws-amplify-react/dist/API/index'>;
}
declare module 'aws-amplify-react/dist/Auth/Authenticator.js' {
  declare module.exports: $Exports<'aws-amplify-react/dist/Auth/Authenticator'>;
}
declare module 'aws-amplify-react/dist/Auth/AuthPiece.js' {
  declare module.exports: $Exports<'aws-amplify-react/dist/Auth/AuthPiece'>;
}
declare module 'aws-amplify-react/dist/Auth/AuthStateWrapper.js' {
  declare module.exports: $Exports<'aws-amplify-react/dist/Auth/AuthStateWrapper'>;
}
declare module 'aws-amplify-react/dist/Auth/ConfirmSignIn.js' {
  declare module.exports: $Exports<'aws-amplify-react/dist/Auth/ConfirmSignIn'>;
}
declare module 'aws-amplify-react/dist/Auth/ConfirmSignUp.js' {
  declare module.exports: $Exports<'aws-amplify-react/dist/Auth/ConfirmSignUp'>;
}
declare module 'aws-amplify-react/dist/Auth/FederatedSignIn.js' {
  declare module.exports: $Exports<'aws-amplify-react/dist/Auth/FederatedSignIn'>;
}
declare module 'aws-amplify-react/dist/Auth/ForgotPassword.js' {
  declare module.exports: $Exports<'aws-amplify-react/dist/Auth/ForgotPassword'>;
}
declare module 'aws-amplify-react/dist/Auth/Greetings.js' {
  declare module.exports: $Exports<'aws-amplify-react/dist/Auth/Greetings'>;
}
declare module 'aws-amplify-react/dist/Auth/index.js' {
  declare module.exports: $Exports<'aws-amplify-react/dist/Auth/index'>;
}
declare module 'aws-amplify-react/dist/Auth/Provider/index.js' {
  declare module.exports: $Exports<'aws-amplify-react/dist/Auth/Provider/index'>;
}
declare module 'aws-amplify-react/dist/Auth/Provider/withAmazon.js' {
  declare module.exports: $Exports<'aws-amplify-react/dist/Auth/Provider/withAmazon'>;
}
declare module 'aws-amplify-react/dist/Auth/Provider/withFacebook.js' {
  declare module.exports: $Exports<'aws-amplify-react/dist/Auth/Provider/withFacebook'>;
}
declare module 'aws-amplify-react/dist/Auth/Provider/withGoogle.js' {
  declare module.exports: $Exports<'aws-amplify-react/dist/Auth/Provider/withGoogle'>;
}
declare module 'aws-amplify-react/dist/Auth/Provider/withOAuth.js' {
  declare module.exports: $Exports<'aws-amplify-react/dist/Auth/Provider/withOAuth'>;
}
declare module 'aws-amplify-react/dist/Auth/RequireNewPassword.js' {
  declare module.exports: $Exports<'aws-amplify-react/dist/Auth/RequireNewPassword'>;
}
declare module 'aws-amplify-react/dist/Auth/SignIn.js' {
  declare module.exports: $Exports<'aws-amplify-react/dist/Auth/SignIn'>;
}
declare module 'aws-amplify-react/dist/Auth/SignUp.js' {
  declare module.exports: $Exports<'aws-amplify-react/dist/Auth/SignUp'>;
}
declare module 'aws-amplify-react/dist/Auth/TOTPSetup.js' {
  declare module.exports: $Exports<'aws-amplify-react/dist/Auth/TOTPSetup'>;
}
declare module 'aws-amplify-react/dist/Auth/VerifyContact.js' {
  declare module.exports: $Exports<'aws-amplify-react/dist/Auth/VerifyContact'>;
}
declare module 'aws-amplify-react/dist/index.js' {
  declare module.exports: $Exports<'aws-amplify-react/dist/index'>;
}
declare module 'aws-amplify-react/dist/Storage/Common.js' {
  declare module.exports: $Exports<'aws-amplify-react/dist/Storage/Common'>;
}
declare module 'aws-amplify-react/dist/Storage/index.js' {
  declare module.exports: $Exports<'aws-amplify-react/dist/Storage/index'>;
}
declare module 'aws-amplify-react/dist/Storage/S3Album.js' {
  declare module.exports: $Exports<'aws-amplify-react/dist/Storage/S3Album'>;
}
declare module 'aws-amplify-react/dist/Storage/S3Image.js' {
  declare module.exports: $Exports<'aws-amplify-react/dist/Storage/S3Image'>;
}
declare module 'aws-amplify-react/dist/Storage/S3Text.js' {
  declare module.exports: $Exports<'aws-amplify-react/dist/Storage/S3Text'>;
}
declare module 'aws-amplify-react/dist/Widget/index.js' {
  declare module.exports: $Exports<'aws-amplify-react/dist/Widget/index'>;
}
declare module 'aws-amplify-react/dist/Widget/PhotoPicker.js' {
  declare module.exports: $Exports<'aws-amplify-react/dist/Widget/PhotoPicker'>;
}
declare module 'aws-amplify-react/dist/Widget/Picker.js' {
  declare module.exports: $Exports<'aws-amplify-react/dist/Widget/Picker'>;
}
declare module 'aws-amplify-react/dist/Widget/SelectMFAType.js' {
  declare module.exports: $Exports<'aws-amplify-react/dist/Widget/SelectMFAType'>;
}
declare module 'aws-amplify-react/dist/Widget/TextPicker.js' {
  declare module.exports: $Exports<'aws-amplify-react/dist/Widget/TextPicker'>;
}
declare module 'aws-amplify-react/dist/Widget/TOTPSetupComp.js' {
  declare module.exports: $Exports<'aws-amplify-react/dist/Widget/TOTPSetupComp'>;
}
