// flow-typed signature: 17845ae574b836e7461c3283323b97a2
// flow-typed version: <<STUB>>/aws-amplify_v^0.2.14/flow_v0.76.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'aws-amplify'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'aws-amplify' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'aws-amplify/dist/aws-amplify' {
  declare module.exports: any;
}

declare module 'aws-amplify/dist/aws-amplify.min' {
  declare module.exports: any;
}

declare module 'aws-amplify/lib/Analytics/Analytics' {
  declare module.exports: any;
}

declare module 'aws-amplify/lib/Analytics/index' {
  declare module.exports: any;
}

declare module 'aws-amplify/lib/Analytics/Providers/AWSAnalyticsProvider' {
  declare module.exports: any;
}

declare module 'aws-amplify/lib/Analytics/SessionManage' {
  declare module.exports: any;
}

declare module 'aws-amplify/lib/Analytics/types/Analytics' {
  declare module.exports: any;
}

declare module 'aws-amplify/lib/Analytics/types/index' {
  declare module.exports: any;
}

declare module 'aws-amplify/lib/Analytics/types/Provider' {
  declare module.exports: any;
}

declare module 'aws-amplify/lib/API/API' {
  declare module.exports: any;
}

declare module 'aws-amplify/lib/API/index' {
  declare module.exports: any;
}

declare module 'aws-amplify/lib/API/RestClient' {
  declare module.exports: any;
}

declare module 'aws-amplify/lib/API/types/index' {
  declare module.exports: any;
}

declare module 'aws-amplify/lib/Auth/Auth' {
  declare module.exports: any;
}

declare module 'aws-amplify/lib/Auth/index' {
  declare module.exports: any;
}

declare module 'aws-amplify/lib/Auth/types/Auth' {
  declare module.exports: any;
}

declare module 'aws-amplify/lib/Auth/types/index' {
  declare module.exports: any;
}

declare module 'aws-amplify/lib/Cache/AsyncStorageCache' {
  declare module.exports: any;
}

declare module 'aws-amplify/lib/Cache/BrowserStorageCache' {
  declare module.exports: any;
}

declare module 'aws-amplify/lib/Cache/index' {
  declare module.exports: any;
}

declare module 'aws-amplify/lib/Cache/InMemoryCache' {
  declare module.exports: any;
}

declare module 'aws-amplify/lib/Cache/reactnative' {
  declare module.exports: any;
}

declare module 'aws-amplify/lib/Cache/StorageCache' {
  declare module.exports: any;
}

declare module 'aws-amplify/lib/Cache/types/Cache' {
  declare module.exports: any;
}

declare module 'aws-amplify/lib/Cache/types/index' {
  declare module.exports: any;
}

declare module 'aws-amplify/lib/Cache/Utils/CacheList' {
  declare module.exports: any;
}

declare module 'aws-amplify/lib/Cache/Utils/CacheUtils' {
  declare module.exports: any;
}

declare module 'aws-amplify/lib/Cache/Utils/index' {
  declare module.exports: any;
}

declare module 'aws-amplify/lib/Common/Builder' {
  declare module.exports: any;
}

declare module 'aws-amplify/lib/Common/ClientDevice/android' {
  declare module.exports: any;
}

declare module 'aws-amplify/lib/Common/ClientDevice/browser' {
  declare module.exports: any;
}

declare module 'aws-amplify/lib/Common/ClientDevice/index' {
  declare module.exports: any;
}

declare module 'aws-amplify/lib/Common/ClientDevice/ios' {
  declare module.exports: any;
}

declare module 'aws-amplify/lib/Common/ClientDevice/reactnative' {
  declare module.exports: any;
}

declare module 'aws-amplify/lib/Common/Errors' {
  declare module.exports: any;
}

declare module 'aws-amplify/lib/Common/Facet' {
  declare module.exports: any;
}

declare module 'aws-amplify/lib/Common/Hub' {
  declare module.exports: any;
}

declare module 'aws-amplify/lib/Common/index' {
  declare module.exports: any;
}

declare module 'aws-amplify/lib/Common/JS' {
  declare module.exports: any;
}

declare module 'aws-amplify/lib/Common/Logger/ConsoleLogger' {
  declare module.exports: any;
}

declare module 'aws-amplify/lib/Common/Logger/index' {
  declare module.exports: any;
}

declare module 'aws-amplify/lib/Common/Logger/logger-interface' {
  declare module.exports: any;
}

declare module 'aws-amplify/lib/Common/OAuthHelper/FacebookOAuth' {
  declare module.exports: any;
}

declare module 'aws-amplify/lib/Common/OAuthHelper/GoogleOAuth' {
  declare module.exports: any;
}

declare module 'aws-amplify/lib/Common/OAuthHelper/index' {
  declare module.exports: any;
}

declare module 'aws-amplify/lib/Common/Parser' {
  declare module.exports: any;
}

declare module 'aws-amplify/lib/Common/Platform/index' {
  declare module.exports: any;
}

declare module 'aws-amplify/lib/Common/Polyfills/index' {
  declare module.exports: any;
}

declare module 'aws-amplify/lib/Common/Polyfills/Polyfills' {
  declare module.exports: any;
}

declare module 'aws-amplify/lib/Common/RNComponents/index' {
  declare module.exports: any;
}

declare module 'aws-amplify/lib/Common/RNComponents/reactnative' {
  declare module.exports: any;
}

declare module 'aws-amplify/lib/Common/Signer' {
  declare module.exports: any;
}

declare module 'aws-amplify/lib/Common/types/AmplifyConfig' {
  declare module.exports: any;
}

declare module 'aws-amplify/lib/Common/types/index' {
  declare module.exports: any;
}

declare module 'aws-amplify/lib/I18n/I18n' {
  declare module.exports: any;
}

declare module 'aws-amplify/lib/I18n/index' {
  declare module.exports: any;
}

declare module 'aws-amplify/lib/I18n/types' {
  declare module.exports: any;
}

declare module 'aws-amplify/lib/index' {
  declare module.exports: any;
}

declare module 'aws-amplify/lib/PubSub/index' {
  declare module.exports: any;
}

declare module 'aws-amplify/lib/PubSub/Providers/AWSIotProvider' {
  declare module.exports: any;
}

declare module 'aws-amplify/lib/PubSub/Providers/index' {
  declare module.exports: any;
}

declare module 'aws-amplify/lib/PubSub/Providers/MqttOverWSProvider' {
  declare module.exports: any;
}

declare module 'aws-amplify/lib/PubSub/Providers/PubSubProvider' {
  declare module.exports: any;
}

declare module 'aws-amplify/lib/PubSub/PubSub' {
  declare module.exports: any;
}

declare module 'aws-amplify/lib/PubSub/types/index' {
  declare module.exports: any;
}

declare module 'aws-amplify/lib/PubSub/types/Provider' {
  declare module.exports: any;
}

declare module 'aws-amplify/lib/PubSub/types/PubSub' {
  declare module.exports: any;
}

declare module 'aws-amplify/lib/Storage/index' {
  declare module.exports: any;
}

declare module 'aws-amplify/lib/Storage/Storage' {
  declare module.exports: any;
}

declare module 'aws-amplify/lib/Storage/types/index' {
  declare module.exports: any;
}

declare module 'aws-amplify/lib/Storage/types/Storage' {
  declare module.exports: any;
}

// Filename aliases
declare module 'aws-amplify/dist/aws-amplify.js' {
  declare module.exports: $Exports<'aws-amplify/dist/aws-amplify'>;
}
declare module 'aws-amplify/dist/aws-amplify.min.js' {
  declare module.exports: $Exports<'aws-amplify/dist/aws-amplify.min'>;
}
declare module 'aws-amplify/lib/Analytics/Analytics.js' {
  declare module.exports: $Exports<'aws-amplify/lib/Analytics/Analytics'>;
}
declare module 'aws-amplify/lib/Analytics/index.js' {
  declare module.exports: $Exports<'aws-amplify/lib/Analytics/index'>;
}
declare module 'aws-amplify/lib/Analytics/Providers/AWSAnalyticsProvider.js' {
  declare module.exports: $Exports<'aws-amplify/lib/Analytics/Providers/AWSAnalyticsProvider'>;
}
declare module 'aws-amplify/lib/Analytics/SessionManage.js' {
  declare module.exports: $Exports<'aws-amplify/lib/Analytics/SessionManage'>;
}
declare module 'aws-amplify/lib/Analytics/types/Analytics.js' {
  declare module.exports: $Exports<'aws-amplify/lib/Analytics/types/Analytics'>;
}
declare module 'aws-amplify/lib/Analytics/types/index.js' {
  declare module.exports: $Exports<'aws-amplify/lib/Analytics/types/index'>;
}
declare module 'aws-amplify/lib/Analytics/types/Provider.js' {
  declare module.exports: $Exports<'aws-amplify/lib/Analytics/types/Provider'>;
}
declare module 'aws-amplify/lib/API/API.js' {
  declare module.exports: $Exports<'aws-amplify/lib/API/API'>;
}
declare module 'aws-amplify/lib/API/index.js' {
  declare module.exports: $Exports<'aws-amplify/lib/API/index'>;
}
declare module 'aws-amplify/lib/API/RestClient.js' {
  declare module.exports: $Exports<'aws-amplify/lib/API/RestClient'>;
}
declare module 'aws-amplify/lib/API/types/index.js' {
  declare module.exports: $Exports<'aws-amplify/lib/API/types/index'>;
}
declare module 'aws-amplify/lib/Auth/Auth.js' {
  declare module.exports: $Exports<'aws-amplify/lib/Auth/Auth'>;
}
declare module 'aws-amplify/lib/Auth/index.js' {
  declare module.exports: $Exports<'aws-amplify/lib/Auth/index'>;
}
declare module 'aws-amplify/lib/Auth/types/Auth.js' {
  declare module.exports: $Exports<'aws-amplify/lib/Auth/types/Auth'>;
}
declare module 'aws-amplify/lib/Auth/types/index.js' {
  declare module.exports: $Exports<'aws-amplify/lib/Auth/types/index'>;
}
declare module 'aws-amplify/lib/Cache/AsyncStorageCache.js' {
  declare module.exports: $Exports<'aws-amplify/lib/Cache/AsyncStorageCache'>;
}
declare module 'aws-amplify/lib/Cache/BrowserStorageCache.js' {
  declare module.exports: $Exports<'aws-amplify/lib/Cache/BrowserStorageCache'>;
}
declare module 'aws-amplify/lib/Cache/index.js' {
  declare module.exports: $Exports<'aws-amplify/lib/Cache/index'>;
}
declare module 'aws-amplify/lib/Cache/InMemoryCache.js' {
  declare module.exports: $Exports<'aws-amplify/lib/Cache/InMemoryCache'>;
}
declare module 'aws-amplify/lib/Cache/reactnative.js' {
  declare module.exports: $Exports<'aws-amplify/lib/Cache/reactnative'>;
}
declare module 'aws-amplify/lib/Cache/StorageCache.js' {
  declare module.exports: $Exports<'aws-amplify/lib/Cache/StorageCache'>;
}
declare module 'aws-amplify/lib/Cache/types/Cache.js' {
  declare module.exports: $Exports<'aws-amplify/lib/Cache/types/Cache'>;
}
declare module 'aws-amplify/lib/Cache/types/index.js' {
  declare module.exports: $Exports<'aws-amplify/lib/Cache/types/index'>;
}
declare module 'aws-amplify/lib/Cache/Utils/CacheList.js' {
  declare module.exports: $Exports<'aws-amplify/lib/Cache/Utils/CacheList'>;
}
declare module 'aws-amplify/lib/Cache/Utils/CacheUtils.js' {
  declare module.exports: $Exports<'aws-amplify/lib/Cache/Utils/CacheUtils'>;
}
declare module 'aws-amplify/lib/Cache/Utils/index.js' {
  declare module.exports: $Exports<'aws-amplify/lib/Cache/Utils/index'>;
}
declare module 'aws-amplify/lib/Common/Builder.js' {
  declare module.exports: $Exports<'aws-amplify/lib/Common/Builder'>;
}
declare module 'aws-amplify/lib/Common/ClientDevice/android.js' {
  declare module.exports: $Exports<'aws-amplify/lib/Common/ClientDevice/android'>;
}
declare module 'aws-amplify/lib/Common/ClientDevice/browser.js' {
  declare module.exports: $Exports<'aws-amplify/lib/Common/ClientDevice/browser'>;
}
declare module 'aws-amplify/lib/Common/ClientDevice/index.js' {
  declare module.exports: $Exports<'aws-amplify/lib/Common/ClientDevice/index'>;
}
declare module 'aws-amplify/lib/Common/ClientDevice/ios.js' {
  declare module.exports: $Exports<'aws-amplify/lib/Common/ClientDevice/ios'>;
}
declare module 'aws-amplify/lib/Common/ClientDevice/reactnative.js' {
  declare module.exports: $Exports<'aws-amplify/lib/Common/ClientDevice/reactnative'>;
}
declare module 'aws-amplify/lib/Common/Errors.js' {
  declare module.exports: $Exports<'aws-amplify/lib/Common/Errors'>;
}
declare module 'aws-amplify/lib/Common/Facet.js' {
  declare module.exports: $Exports<'aws-amplify/lib/Common/Facet'>;
}
declare module 'aws-amplify/lib/Common/Hub.js' {
  declare module.exports: $Exports<'aws-amplify/lib/Common/Hub'>;
}
declare module 'aws-amplify/lib/Common/index.js' {
  declare module.exports: $Exports<'aws-amplify/lib/Common/index'>;
}
declare module 'aws-amplify/lib/Common/JS.js' {
  declare module.exports: $Exports<'aws-amplify/lib/Common/JS'>;
}
declare module 'aws-amplify/lib/Common/Logger/ConsoleLogger.js' {
  declare module.exports: $Exports<'aws-amplify/lib/Common/Logger/ConsoleLogger'>;
}
declare module 'aws-amplify/lib/Common/Logger/index.js' {
  declare module.exports: $Exports<'aws-amplify/lib/Common/Logger/index'>;
}
declare module 'aws-amplify/lib/Common/Logger/logger-interface.js' {
  declare module.exports: $Exports<'aws-amplify/lib/Common/Logger/logger-interface'>;
}
declare module 'aws-amplify/lib/Common/OAuthHelper/FacebookOAuth.js' {
  declare module.exports: $Exports<'aws-amplify/lib/Common/OAuthHelper/FacebookOAuth'>;
}
declare module 'aws-amplify/lib/Common/OAuthHelper/GoogleOAuth.js' {
  declare module.exports: $Exports<'aws-amplify/lib/Common/OAuthHelper/GoogleOAuth'>;
}
declare module 'aws-amplify/lib/Common/OAuthHelper/index.js' {
  declare module.exports: $Exports<'aws-amplify/lib/Common/OAuthHelper/index'>;
}
declare module 'aws-amplify/lib/Common/Parser.js' {
  declare module.exports: $Exports<'aws-amplify/lib/Common/Parser'>;
}
declare module 'aws-amplify/lib/Common/Platform/index.js' {
  declare module.exports: $Exports<'aws-amplify/lib/Common/Platform/index'>;
}
declare module 'aws-amplify/lib/Common/Polyfills/index.js' {
  declare module.exports: $Exports<'aws-amplify/lib/Common/Polyfills/index'>;
}
declare module 'aws-amplify/lib/Common/Polyfills/Polyfills.js' {
  declare module.exports: $Exports<'aws-amplify/lib/Common/Polyfills/Polyfills'>;
}
declare module 'aws-amplify/lib/Common/RNComponents/index.js' {
  declare module.exports: $Exports<'aws-amplify/lib/Common/RNComponents/index'>;
}
declare module 'aws-amplify/lib/Common/RNComponents/reactnative.js' {
  declare module.exports: $Exports<'aws-amplify/lib/Common/RNComponents/reactnative'>;
}
declare module 'aws-amplify/lib/Common/Signer.js' {
  declare module.exports: $Exports<'aws-amplify/lib/Common/Signer'>;
}
declare module 'aws-amplify/lib/Common/types/AmplifyConfig.js' {
  declare module.exports: $Exports<'aws-amplify/lib/Common/types/AmplifyConfig'>;
}
declare module 'aws-amplify/lib/Common/types/index.js' {
  declare module.exports: $Exports<'aws-amplify/lib/Common/types/index'>;
}
declare module 'aws-amplify/lib/I18n/I18n.js' {
  declare module.exports: $Exports<'aws-amplify/lib/I18n/I18n'>;
}
declare module 'aws-amplify/lib/I18n/index.js' {
  declare module.exports: $Exports<'aws-amplify/lib/I18n/index'>;
}
declare module 'aws-amplify/lib/I18n/types.js' {
  declare module.exports: $Exports<'aws-amplify/lib/I18n/types'>;
}
declare module 'aws-amplify/lib/index.js' {
  declare module.exports: $Exports<'aws-amplify/lib/index'>;
}
declare module 'aws-amplify/lib/PubSub/index.js' {
  declare module.exports: $Exports<'aws-amplify/lib/PubSub/index'>;
}
declare module 'aws-amplify/lib/PubSub/Providers/AWSIotProvider.js' {
  declare module.exports: $Exports<'aws-amplify/lib/PubSub/Providers/AWSIotProvider'>;
}
declare module 'aws-amplify/lib/PubSub/Providers/index.js' {
  declare module.exports: $Exports<'aws-amplify/lib/PubSub/Providers/index'>;
}
declare module 'aws-amplify/lib/PubSub/Providers/MqttOverWSProvider.js' {
  declare module.exports: $Exports<'aws-amplify/lib/PubSub/Providers/MqttOverWSProvider'>;
}
declare module 'aws-amplify/lib/PubSub/Providers/PubSubProvider.js' {
  declare module.exports: $Exports<'aws-amplify/lib/PubSub/Providers/PubSubProvider'>;
}
declare module 'aws-amplify/lib/PubSub/PubSub.js' {
  declare module.exports: $Exports<'aws-amplify/lib/PubSub/PubSub'>;
}
declare module 'aws-amplify/lib/PubSub/types/index.js' {
  declare module.exports: $Exports<'aws-amplify/lib/PubSub/types/index'>;
}
declare module 'aws-amplify/lib/PubSub/types/Provider.js' {
  declare module.exports: $Exports<'aws-amplify/lib/PubSub/types/Provider'>;
}
declare module 'aws-amplify/lib/PubSub/types/PubSub.js' {
  declare module.exports: $Exports<'aws-amplify/lib/PubSub/types/PubSub'>;
}
declare module 'aws-amplify/lib/Storage/index.js' {
  declare module.exports: $Exports<'aws-amplify/lib/Storage/index'>;
}
declare module 'aws-amplify/lib/Storage/Storage.js' {
  declare module.exports: $Exports<'aws-amplify/lib/Storage/Storage'>;
}
declare module 'aws-amplify/lib/Storage/types/index.js' {
  declare module.exports: $Exports<'aws-amplify/lib/Storage/types/index'>;
}
declare module 'aws-amplify/lib/Storage/types/Storage.js' {
  declare module.exports: $Exports<'aws-amplify/lib/Storage/types/Storage'>;
}
