// flow-typed signature: 1833bc04cad0a77bc14a91ac29a6bcea
// flow-typed version: <<STUB>>/codemirror-spell-checker_v^1.1.2/flow_v0.76.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'codemirror-spell-checker'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'codemirror-spell-checker' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'codemirror-spell-checker/debug/spell-checker.debug' {
  declare module.exports: any;
}

declare module 'codemirror-spell-checker/debug/spell-checker' {
  declare module.exports: any;
}

declare module 'codemirror-spell-checker/dist/spell-checker.min' {
  declare module.exports: any;
}

declare module 'codemirror-spell-checker/gulpfile' {
  declare module.exports: any;
}

declare module 'codemirror-spell-checker/src/js/spell-checker' {
  declare module.exports: any;
}

// Filename aliases
declare module 'codemirror-spell-checker/debug/spell-checker.debug.js' {
  declare module.exports: $Exports<'codemirror-spell-checker/debug/spell-checker.debug'>;
}
declare module 'codemirror-spell-checker/debug/spell-checker.js' {
  declare module.exports: $Exports<'codemirror-spell-checker/debug/spell-checker'>;
}
declare module 'codemirror-spell-checker/dist/spell-checker.min.js' {
  declare module.exports: $Exports<'codemirror-spell-checker/dist/spell-checker.min'>;
}
declare module 'codemirror-spell-checker/gulpfile.js' {
  declare module.exports: $Exports<'codemirror-spell-checker/gulpfile'>;
}
declare module 'codemirror-spell-checker/src/js/spell-checker.js' {
  declare module.exports: $Exports<'codemirror-spell-checker/src/js/spell-checker'>;
}
