// flow-typed signature: cb9697251a766142af0c6f5e16559377
// flow-typed version: <<STUB>>/color-string_v^1.5.3/flow_v0.97.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'color-string'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'color-string' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */


// Filename aliases
declare module 'color-string/index' {
  declare module.exports: $Exports<'color-string'>;
}
declare module 'color-string/index.js' {
  declare module.exports: $Exports<'color-string'>;
}
