// flow-typed signature: d165cf3fa886f5ef04fd645d0ac7bbd0
// flow-typed version: <<STUB>>/firepad_vgit+ssh://git@github.com/rocksauce/firepad.git#feature/importCodeMirror/flow_v0.76.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'firepad'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'firepad' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'firepad/dist/firepad' {
  declare module.exports: any;
}

declare module 'firepad/dist/firepad.min' {
  declare module.exports: any;
}

declare module 'firepad/Gruntfile' {
  declare module.exports: any;
}

declare module 'firepad/lib/annotation-list' {
  declare module.exports: any;
}

declare module 'firepad/lib/client' {
  declare module.exports: any;
}

declare module 'firepad/lib/constants' {
  declare module.exports: any;
}

declare module 'firepad/lib/cursor' {
  declare module.exports: any;
}

declare module 'firepad/lib/editor-client' {
  declare module.exports: any;
}

declare module 'firepad/lib/entity-manager' {
  declare module.exports: any;
}

declare module 'firepad/lib/entity' {
  declare module.exports: any;
}

declare module 'firepad/lib/firebase-adapter' {
  declare module.exports: any;
}

declare module 'firepad/lib/firepad' {
  declare module.exports: any;
}

declare module 'firepad/lib/formatting' {
  declare module.exports: any;
}

declare module 'firepad/lib/fountain' {
  declare module.exports: any;
}

declare module 'firepad/lib/headless' {
  declare module.exports: any;
}

declare module 'firepad/lib/line-formatting' {
  declare module.exports: any;
}

declare module 'firepad/lib/line' {
  declare module.exports: any;
}

declare module 'firepad/lib/parse-html' {
  declare module.exports: any;
}

declare module 'firepad/lib/rich-text-codemirror-adapter' {
  declare module.exports: any;
}

declare module 'firepad/lib/rich-text-codemirror' {
  declare module.exports: any;
}

declare module 'firepad/lib/rich-text-toolbar' {
  declare module.exports: any;
}

declare module 'firepad/lib/screenplay-toolbar' {
  declare module.exports: any;
}

declare module 'firepad/lib/serialize-html' {
  declare module.exports: any;
}

declare module 'firepad/lib/serialize-json' {
  declare module.exports: any;
}

declare module 'firepad/lib/serialize-text' {
  declare module.exports: any;
}

declare module 'firepad/lib/span' {
  declare module.exports: any;
}

declare module 'firepad/lib/text-op' {
  declare module.exports: any;
}

declare module 'firepad/lib/text-operation' {
  declare module.exports: any;
}

declare module 'firepad/lib/text-pieces-to-inserts' {
  declare module.exports: any;
}

declare module 'firepad/lib/text' {
  declare module.exports: any;
}

declare module 'firepad/lib/undo-manager' {
  declare module.exports: any;
}

declare module 'firepad/lib/utils' {
  declare module.exports: any;
}

declare module 'firepad/lib/wrapped-operation' {
  declare module.exports: any;
}

// Filename aliases
declare module 'firepad/dist/firepad.js' {
  declare module.exports: $Exports<'firepad/dist/firepad'>;
}
declare module 'firepad/dist/firepad.min.js' {
  declare module.exports: $Exports<'firepad/dist/firepad.min'>;
}
declare module 'firepad/Gruntfile.js' {
  declare module.exports: $Exports<'firepad/Gruntfile'>;
}
declare module 'firepad/lib/annotation-list.js' {
  declare module.exports: $Exports<'firepad/lib/annotation-list'>;
}
declare module 'firepad/lib/client.js' {
  declare module.exports: $Exports<'firepad/lib/client'>;
}
declare module 'firepad/lib/constants.js' {
  declare module.exports: $Exports<'firepad/lib/constants'>;
}
declare module 'firepad/lib/cursor.js' {
  declare module.exports: $Exports<'firepad/lib/cursor'>;
}
declare module 'firepad/lib/editor-client.js' {
  declare module.exports: $Exports<'firepad/lib/editor-client'>;
}
declare module 'firepad/lib/entity-manager.js' {
  declare module.exports: $Exports<'firepad/lib/entity-manager'>;
}
declare module 'firepad/lib/entity.js' {
  declare module.exports: $Exports<'firepad/lib/entity'>;
}
declare module 'firepad/lib/firebase-adapter.js' {
  declare module.exports: $Exports<'firepad/lib/firebase-adapter'>;
}
declare module 'firepad/lib/firepad.js' {
  declare module.exports: $Exports<'firepad/lib/firepad'>;
}
declare module 'firepad/lib/formatting.js' {
  declare module.exports: $Exports<'firepad/lib/formatting'>;
}
declare module 'firepad/lib/fountain.js' {
  declare module.exports: $Exports<'firepad/lib/fountain'>;
}
declare module 'firepad/lib/headless.js' {
  declare module.exports: $Exports<'firepad/lib/headless'>;
}
declare module 'firepad/lib/line-formatting.js' {
  declare module.exports: $Exports<'firepad/lib/line-formatting'>;
}
declare module 'firepad/lib/line.js' {
  declare module.exports: $Exports<'firepad/lib/line'>;
}
declare module 'firepad/lib/parse-html.js' {
  declare module.exports: $Exports<'firepad/lib/parse-html'>;
}
declare module 'firepad/lib/rich-text-codemirror-adapter.js' {
  declare module.exports: $Exports<'firepad/lib/rich-text-codemirror-adapter'>;
}
declare module 'firepad/lib/rich-text-codemirror.js' {
  declare module.exports: $Exports<'firepad/lib/rich-text-codemirror'>;
}
declare module 'firepad/lib/rich-text-toolbar.js' {
  declare module.exports: $Exports<'firepad/lib/rich-text-toolbar'>;
}
declare module 'firepad/lib/screenplay-toolbar.js' {
  declare module.exports: $Exports<'firepad/lib/screenplay-toolbar'>;
}
declare module 'firepad/lib/serialize-html.js' {
  declare module.exports: $Exports<'firepad/lib/serialize-html'>;
}
declare module 'firepad/lib/serialize-json.js' {
  declare module.exports: $Exports<'firepad/lib/serialize-json'>;
}
declare module 'firepad/lib/serialize-text.js' {
  declare module.exports: $Exports<'firepad/lib/serialize-text'>;
}
declare module 'firepad/lib/span.js' {
  declare module.exports: $Exports<'firepad/lib/span'>;
}
declare module 'firepad/lib/text-op.js' {
  declare module.exports: $Exports<'firepad/lib/text-op'>;
}
declare module 'firepad/lib/text-operation.js' {
  declare module.exports: $Exports<'firepad/lib/text-operation'>;
}
declare module 'firepad/lib/text-pieces-to-inserts.js' {
  declare module.exports: $Exports<'firepad/lib/text-pieces-to-inserts'>;
}
declare module 'firepad/lib/text.js' {
  declare module.exports: $Exports<'firepad/lib/text'>;
}
declare module 'firepad/lib/undo-manager.js' {
  declare module.exports: $Exports<'firepad/lib/undo-manager'>;
}
declare module 'firepad/lib/utils.js' {
  declare module.exports: $Exports<'firepad/lib/utils'>;
}
declare module 'firepad/lib/wrapped-operation.js' {
  declare module.exports: $Exports<'firepad/lib/wrapped-operation'>;
}
