// flow-typed signature: 87165ebd8c1cb5454dee5451b9279ccf
// flow-typed version: <<STUB>>/formik-material-ui_v0.0.16/flow_v0.97.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'formik-material-ui'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'formik-material-ui' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'formik-material-ui/dist/formik-material-ui.es6' {
  declare module.exports: any;
}

declare module 'formik-material-ui/dist/index' {
  declare module.exports: any;
}

// Filename aliases
declare module 'formik-material-ui/dist/formik-material-ui.es6.js' {
  declare module.exports: $Exports<'formik-material-ui/dist/formik-material-ui.es6'>;
}
declare module 'formik-material-ui/dist/index.js' {
  declare module.exports: $Exports<'formik-material-ui/dist/index'>;
}
