// flow-typed signature: 3b12437a7602b18d2a7b9519b38a4ef9
// flow-typed version: <<STUB>>/git_v^0.1.5/flow_v0.76.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'git'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'git' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'git/benchmarks/benchmark' {
  declare module.exports: any;
}

declare module 'git/lib/diff/block' {
  declare module.exports: any;
}

declare module 'git/lib/diff/callbacks' {
  declare module.exports: any;
}

declare module 'git/lib/diff/change' {
  declare module.exports: any;
}

declare module 'git/lib/diff/diff' {
  declare module.exports: any;
}

declare module 'git/lib/diff/hunk' {
  declare module.exports: any;
}

declare module 'git/lib/git/actor' {
  declare module.exports: any;
}

declare module 'git/lib/git/binary_parser' {
  declare module.exports: any;
}

declare module 'git/lib/git/blame_line' {
  declare module.exports: any;
}

declare module 'git/lib/git/blame' {
  declare module.exports: any;
}

declare module 'git/lib/git/blob' {
  declare module.exports: any;
}

declare module 'git/lib/git/commit_stats' {
  declare module.exports: any;
}

declare module 'git/lib/git/commit' {
  declare module.exports: any;
}

declare module 'git/lib/git/config' {
  declare module.exports: any;
}

declare module 'git/lib/git/diff' {
  declare module.exports: any;
}

declare module 'git/lib/git/file_index' {
  declare module.exports: any;
}

declare module 'git/lib/git/file_window' {
  declare module.exports: any;
}

declare module 'git/lib/git/git_file_operations' {
  declare module.exports: any;
}

declare module 'git/lib/git/git_index' {
  declare module.exports: any;
}

declare module 'git/lib/git/git_object' {
  declare module.exports: any;
}

declare module 'git/lib/git/git' {
  declare module.exports: any;
}

declare module 'git/lib/git/head' {
  declare module.exports: any;
}

declare module 'git/lib/git/index' {
  declare module.exports: any;
}

declare module 'git/lib/git/internal/directory_entry' {
  declare module.exports: any;
}

declare module 'git/lib/git/internal/git_blob' {
  declare module.exports: any;
}

declare module 'git/lib/git/internal/git_commit' {
  declare module.exports: any;
}

declare module 'git/lib/git/internal/git_tag' {
  declare module.exports: any;
}

declare module 'git/lib/git/internal/git_tree' {
  declare module.exports: any;
}

declare module 'git/lib/git/loose_storage' {
  declare module.exports: any;
}

declare module 'git/lib/git/merge' {
  declare module.exports: any;
}

declare module 'git/lib/git/pack_storage' {
  declare module.exports: any;
}

declare module 'git/lib/git/raw_object' {
  declare module.exports: any;
}

declare module 'git/lib/git/ref' {
  declare module.exports: any;
}

declare module 'git/lib/git/remote' {
  declare module.exports: any;
}

declare module 'git/lib/git/repo' {
  declare module.exports: any;
}

declare module 'git/lib/git/repository' {
  declare module.exports: any;
}

declare module 'git/lib/git/status_file' {
  declare module.exports: any;
}

declare module 'git/lib/git/status' {
  declare module.exports: any;
}

declare module 'git/lib/git/sub_module' {
  declare module.exports: any;
}

declare module 'git/lib/git/tag' {
  declare module.exports: any;
}

declare module 'git/lib/git/tree' {
  declare module.exports: any;
}

declare module 'git/lib/git/user_info' {
  declare module.exports: any;
}

declare module 'git/lib/sprintf/sprintf' {
  declare module.exports: any;
}

declare module 'git/lib/zlib/zlib' {
  declare module.exports: any;
}

// Filename aliases
declare module 'git/benchmarks/benchmark.js' {
  declare module.exports: $Exports<'git/benchmarks/benchmark'>;
}
declare module 'git/lib/diff/block.js' {
  declare module.exports: $Exports<'git/lib/diff/block'>;
}
declare module 'git/lib/diff/callbacks.js' {
  declare module.exports: $Exports<'git/lib/diff/callbacks'>;
}
declare module 'git/lib/diff/change.js' {
  declare module.exports: $Exports<'git/lib/diff/change'>;
}
declare module 'git/lib/diff/diff.js' {
  declare module.exports: $Exports<'git/lib/diff/diff'>;
}
declare module 'git/lib/diff/hunk.js' {
  declare module.exports: $Exports<'git/lib/diff/hunk'>;
}
declare module 'git/lib/git/actor.js' {
  declare module.exports: $Exports<'git/lib/git/actor'>;
}
declare module 'git/lib/git/binary_parser.js' {
  declare module.exports: $Exports<'git/lib/git/binary_parser'>;
}
declare module 'git/lib/git/blame_line.js' {
  declare module.exports: $Exports<'git/lib/git/blame_line'>;
}
declare module 'git/lib/git/blame.js' {
  declare module.exports: $Exports<'git/lib/git/blame'>;
}
declare module 'git/lib/git/blob.js' {
  declare module.exports: $Exports<'git/lib/git/blob'>;
}
declare module 'git/lib/git/commit_stats.js' {
  declare module.exports: $Exports<'git/lib/git/commit_stats'>;
}
declare module 'git/lib/git/commit.js' {
  declare module.exports: $Exports<'git/lib/git/commit'>;
}
declare module 'git/lib/git/config.js' {
  declare module.exports: $Exports<'git/lib/git/config'>;
}
declare module 'git/lib/git/diff.js' {
  declare module.exports: $Exports<'git/lib/git/diff'>;
}
declare module 'git/lib/git/file_index.js' {
  declare module.exports: $Exports<'git/lib/git/file_index'>;
}
declare module 'git/lib/git/file_window.js' {
  declare module.exports: $Exports<'git/lib/git/file_window'>;
}
declare module 'git/lib/git/git_file_operations.js' {
  declare module.exports: $Exports<'git/lib/git/git_file_operations'>;
}
declare module 'git/lib/git/git_index.js' {
  declare module.exports: $Exports<'git/lib/git/git_index'>;
}
declare module 'git/lib/git/git_object.js' {
  declare module.exports: $Exports<'git/lib/git/git_object'>;
}
declare module 'git/lib/git/git.js' {
  declare module.exports: $Exports<'git/lib/git/git'>;
}
declare module 'git/lib/git/head.js' {
  declare module.exports: $Exports<'git/lib/git/head'>;
}
declare module 'git/lib/git/index.js' {
  declare module.exports: $Exports<'git/lib/git/index'>;
}
declare module 'git/lib/git/internal/directory_entry.js' {
  declare module.exports: $Exports<'git/lib/git/internal/directory_entry'>;
}
declare module 'git/lib/git/internal/git_blob.js' {
  declare module.exports: $Exports<'git/lib/git/internal/git_blob'>;
}
declare module 'git/lib/git/internal/git_commit.js' {
  declare module.exports: $Exports<'git/lib/git/internal/git_commit'>;
}
declare module 'git/lib/git/internal/git_tag.js' {
  declare module.exports: $Exports<'git/lib/git/internal/git_tag'>;
}
declare module 'git/lib/git/internal/git_tree.js' {
  declare module.exports: $Exports<'git/lib/git/internal/git_tree'>;
}
declare module 'git/lib/git/loose_storage.js' {
  declare module.exports: $Exports<'git/lib/git/loose_storage'>;
}
declare module 'git/lib/git/merge.js' {
  declare module.exports: $Exports<'git/lib/git/merge'>;
}
declare module 'git/lib/git/pack_storage.js' {
  declare module.exports: $Exports<'git/lib/git/pack_storage'>;
}
declare module 'git/lib/git/raw_object.js' {
  declare module.exports: $Exports<'git/lib/git/raw_object'>;
}
declare module 'git/lib/git/ref.js' {
  declare module.exports: $Exports<'git/lib/git/ref'>;
}
declare module 'git/lib/git/remote.js' {
  declare module.exports: $Exports<'git/lib/git/remote'>;
}
declare module 'git/lib/git/repo.js' {
  declare module.exports: $Exports<'git/lib/git/repo'>;
}
declare module 'git/lib/git/repository.js' {
  declare module.exports: $Exports<'git/lib/git/repository'>;
}
declare module 'git/lib/git/status_file.js' {
  declare module.exports: $Exports<'git/lib/git/status_file'>;
}
declare module 'git/lib/git/status.js' {
  declare module.exports: $Exports<'git/lib/git/status'>;
}
declare module 'git/lib/git/sub_module.js' {
  declare module.exports: $Exports<'git/lib/git/sub_module'>;
}
declare module 'git/lib/git/tag.js' {
  declare module.exports: $Exports<'git/lib/git/tag'>;
}
declare module 'git/lib/git/tree.js' {
  declare module.exports: $Exports<'git/lib/git/tree'>;
}
declare module 'git/lib/git/user_info.js' {
  declare module.exports: $Exports<'git/lib/git/user_info'>;
}
declare module 'git/lib/sprintf/sprintf.js' {
  declare module.exports: $Exports<'git/lib/sprintf/sprintf'>;
}
declare module 'git/lib/zlib/zlib.js' {
  declare module.exports: $Exports<'git/lib/zlib/zlib'>;
}
