// flow-typed signature: 7c682f6436b920ddd0430f1759f85e77
// flow-typed version: <<STUB>>/isarray_v^2.0.4/flow_v0.76.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'isarray'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'isarray' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */


// Filename aliases
declare module 'isarray/index' {
  declare module.exports: $Exports<'isarray'>;
}
declare module 'isarray/index.js' {
  declare module.exports: $Exports<'isarray'>;
}
