// flow-typed signature: ff44e5d936a35e81e526b19c4259041f
// flow-typed version: <<STUB>>/material-ui-chip-input_v^1.0.0-beta.15/flow_v0.97.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'material-ui-chip-input'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'material-ui-chip-input' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'material-ui-chip-input/lib/ChipInput' {
  declare module.exports: any;
}

declare module 'material-ui-chip-input/lib/ChipInput.spec' {
  declare module.exports: any;
}

// Filename aliases
declare module 'material-ui-chip-input/lib/ChipInput.js' {
  declare module.exports: $Exports<'material-ui-chip-input/lib/ChipInput'>;
}
declare module 'material-ui-chip-input/lib/ChipInput.spec.js' {
  declare module.exports: $Exports<'material-ui-chip-input/lib/ChipInput.spec'>;
}
