// flow-typed signature: 98b23fb3edbd7d5978b5ec8efa722ec7
// flow-typed version: <<STUB>>/mui-virtualized-table_v^2.2.2/flow_v0.97.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'mui-virtualized-table'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'mui-virtualized-table' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'mui-virtualized-table/dist/index' {
  declare module.exports: any;
}

declare module 'mui-virtualized-table/dist/utils' {
  declare module.exports: any;
}

declare module 'mui-virtualized-table/dist/utils.test' {
  declare module.exports: any;
}

// Filename aliases
declare module 'mui-virtualized-table/dist/index.js' {
  declare module.exports: $Exports<'mui-virtualized-table/dist/index'>;
}
declare module 'mui-virtualized-table/dist/utils.js' {
  declare module.exports: $Exports<'mui-virtualized-table/dist/utils'>;
}
declare module 'mui-virtualized-table/dist/utils.test.js' {
  declare module.exports: $Exports<'mui-virtualized-table/dist/utils.test'>;
}
