// flow-typed signature: 41561488be9b855408b644da84bd89aa
// flow-typed version: <<STUB>>/pdfkit_vgit://github.com/andybar2/pdfkit.git#convert-es6/flow_v0.77.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'pdfkit'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'pdfkit' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'pdfkit/demo/browser' {
  declare module.exports: any;
}

declare module 'pdfkit/demo/test' {
  declare module.exports: any;
}

declare module 'pdfkit/demo/tiger' {
  declare module.exports: any;
}

declare module 'pdfkit/docs/generate_website' {
  declare module.exports: any;
}

declare module 'pdfkit/docs/generate' {
  declare module.exports: any;
}

declare module 'pdfkit/js/pdfkit.es5' {
  declare module.exports: any;
}

declare module 'pdfkit/js/pdfkit.esnext' {
  declare module.exports: any;
}

declare module 'pdfkit/js/pdfkit' {
  declare module.exports: any;
}

declare module 'pdfkit/lib/abstract_reference' {
  declare module.exports: any;
}

declare module 'pdfkit/lib/data' {
  declare module.exports: any;
}

declare module 'pdfkit/lib/document' {
  declare module.exports: any;
}

declare module 'pdfkit/lib/font_factory' {
  declare module.exports: any;
}

declare module 'pdfkit/lib/font' {
  declare module.exports: any;
}

declare module 'pdfkit/lib/font/afm' {
  declare module.exports: any;
}

declare module 'pdfkit/lib/font/embedded' {
  declare module.exports: any;
}

declare module 'pdfkit/lib/font/standard' {
  declare module.exports: any;
}

declare module 'pdfkit/lib/gradient' {
  declare module.exports: any;
}

declare module 'pdfkit/lib/image' {
  declare module.exports: any;
}

declare module 'pdfkit/lib/image/jpeg' {
  declare module.exports: any;
}

declare module 'pdfkit/lib/image/png' {
  declare module.exports: any;
}

declare module 'pdfkit/lib/line_wrapper' {
  declare module.exports: any;
}

declare module 'pdfkit/lib/mixins/annotations' {
  declare module.exports: any;
}

declare module 'pdfkit/lib/mixins/color' {
  declare module.exports: any;
}

declare module 'pdfkit/lib/mixins/fonts' {
  declare module.exports: any;
}

declare module 'pdfkit/lib/mixins/images' {
  declare module.exports: any;
}

declare module 'pdfkit/lib/mixins/outline' {
  declare module.exports: any;
}

declare module 'pdfkit/lib/mixins/text' {
  declare module.exports: any;
}

declare module 'pdfkit/lib/mixins/vector' {
  declare module.exports: any;
}

declare module 'pdfkit/lib/object' {
  declare module.exports: any;
}

declare module 'pdfkit/lib/outline' {
  declare module.exports: any;
}

declare module 'pdfkit/lib/page' {
  declare module.exports: any;
}

declare module 'pdfkit/lib/path' {
  declare module.exports: any;
}

declare module 'pdfkit/lib/reference' {
  declare module.exports: any;
}

declare module 'pdfkit/rollup.config' {
  declare module.exports: any;
}

declare module 'pdfkit/tests/fonts.spec' {
  declare module.exports: any;
}

declare module 'pdfkit/tests/helpers' {
  declare module.exports: any;
}

declare module 'pdfkit/tests/images/bee' {
  declare module.exports: any;
}

declare module 'pdfkit/tests/pdfmake/absolute.spec' {
  declare module.exports: any;
}

declare module 'pdfkit/tests/pdfmake/background.spec' {
  declare module.exports: any;
}

declare module 'pdfkit/tests/pdfmake/basics.spec' {
  declare module.exports: any;
}

declare module 'pdfkit/tests/pdfmake/columns_simple.spec' {
  declare module.exports: any;
}

declare module 'pdfkit/tests/pdfmake/images.spec' {
  declare module.exports: any;
}

declare module 'pdfkit/tests/pdfmake/lists.spec' {
  declare module.exports: any;
}

declare module 'pdfkit/tests/pdfmake/page_references.spec' {
  declare module.exports: any;
}

declare module 'pdfkit/tests/pdfmake/qrcode.spec' {
  declare module.exports: any;
}

declare module 'pdfkit/tests/pdfmake/tables.spec' {
  declare module.exports: any;
}

declare module 'pdfkit/tests/pdfmake/text_decorations.spec' {
  declare module.exports: any;
}

declare module 'pdfkit/tests/pdfmake/toc.spec' {
  declare module.exports: any;
}

declare module 'pdfkit/tests/pdfmake/watermark.spec' {
  declare module.exports: any;
}

declare module 'pdfkit/tests/text.spec' {
  declare module.exports: any;
}

declare module 'pdfkit/tests/unit/color.spec' {
  declare module.exports: any;
}

declare module 'pdfkit/tests/vector.spec' {
  declare module.exports: any;
}

// Filename aliases
declare module 'pdfkit/demo/browser.js' {
  declare module.exports: $Exports<'pdfkit/demo/browser'>;
}
declare module 'pdfkit/demo/test.js' {
  declare module.exports: $Exports<'pdfkit/demo/test'>;
}
declare module 'pdfkit/demo/tiger.js' {
  declare module.exports: $Exports<'pdfkit/demo/tiger'>;
}
declare module 'pdfkit/docs/generate_website.js' {
  declare module.exports: $Exports<'pdfkit/docs/generate_website'>;
}
declare module 'pdfkit/docs/generate.js' {
  declare module.exports: $Exports<'pdfkit/docs/generate'>;
}
declare module 'pdfkit/index' {
  declare module.exports: $Exports<'pdfkit'>;
}
declare module 'pdfkit/index.js' {
  declare module.exports: $Exports<'pdfkit'>;
}
declare module 'pdfkit/js/pdfkit.es5.js' {
  declare module.exports: $Exports<'pdfkit/js/pdfkit.es5'>;
}
declare module 'pdfkit/js/pdfkit.esnext.js' {
  declare module.exports: $Exports<'pdfkit/js/pdfkit.esnext'>;
}
declare module 'pdfkit/js/pdfkit.js' {
  declare module.exports: $Exports<'pdfkit/js/pdfkit'>;
}
declare module 'pdfkit/lib/abstract_reference.js' {
  declare module.exports: $Exports<'pdfkit/lib/abstract_reference'>;
}
declare module 'pdfkit/lib/data.js' {
  declare module.exports: $Exports<'pdfkit/lib/data'>;
}
declare module 'pdfkit/lib/document.js' {
  declare module.exports: $Exports<'pdfkit/lib/document'>;
}
declare module 'pdfkit/lib/font_factory.js' {
  declare module.exports: $Exports<'pdfkit/lib/font_factory'>;
}
declare module 'pdfkit/lib/font.js' {
  declare module.exports: $Exports<'pdfkit/lib/font'>;
}
declare module 'pdfkit/lib/font/afm.js' {
  declare module.exports: $Exports<'pdfkit/lib/font/afm'>;
}
declare module 'pdfkit/lib/font/embedded.js' {
  declare module.exports: $Exports<'pdfkit/lib/font/embedded'>;
}
declare module 'pdfkit/lib/font/standard.js' {
  declare module.exports: $Exports<'pdfkit/lib/font/standard'>;
}
declare module 'pdfkit/lib/gradient.js' {
  declare module.exports: $Exports<'pdfkit/lib/gradient'>;
}
declare module 'pdfkit/lib/image.js' {
  declare module.exports: $Exports<'pdfkit/lib/image'>;
}
declare module 'pdfkit/lib/image/jpeg.js' {
  declare module.exports: $Exports<'pdfkit/lib/image/jpeg'>;
}
declare module 'pdfkit/lib/image/png.js' {
  declare module.exports: $Exports<'pdfkit/lib/image/png'>;
}
declare module 'pdfkit/lib/line_wrapper.js' {
  declare module.exports: $Exports<'pdfkit/lib/line_wrapper'>;
}
declare module 'pdfkit/lib/mixins/annotations.js' {
  declare module.exports: $Exports<'pdfkit/lib/mixins/annotations'>;
}
declare module 'pdfkit/lib/mixins/color.js' {
  declare module.exports: $Exports<'pdfkit/lib/mixins/color'>;
}
declare module 'pdfkit/lib/mixins/fonts.js' {
  declare module.exports: $Exports<'pdfkit/lib/mixins/fonts'>;
}
declare module 'pdfkit/lib/mixins/images.js' {
  declare module.exports: $Exports<'pdfkit/lib/mixins/images'>;
}
declare module 'pdfkit/lib/mixins/outline.js' {
  declare module.exports: $Exports<'pdfkit/lib/mixins/outline'>;
}
declare module 'pdfkit/lib/mixins/text.js' {
  declare module.exports: $Exports<'pdfkit/lib/mixins/text'>;
}
declare module 'pdfkit/lib/mixins/vector.js' {
  declare module.exports: $Exports<'pdfkit/lib/mixins/vector'>;
}
declare module 'pdfkit/lib/object.js' {
  declare module.exports: $Exports<'pdfkit/lib/object'>;
}
declare module 'pdfkit/lib/outline.js' {
  declare module.exports: $Exports<'pdfkit/lib/outline'>;
}
declare module 'pdfkit/lib/page.js' {
  declare module.exports: $Exports<'pdfkit/lib/page'>;
}
declare module 'pdfkit/lib/path.js' {
  declare module.exports: $Exports<'pdfkit/lib/path'>;
}
declare module 'pdfkit/lib/reference.js' {
  declare module.exports: $Exports<'pdfkit/lib/reference'>;
}
declare module 'pdfkit/rollup.config.js' {
  declare module.exports: $Exports<'pdfkit/rollup.config'>;
}
declare module 'pdfkit/tests/fonts.spec.js' {
  declare module.exports: $Exports<'pdfkit/tests/fonts.spec'>;
}
declare module 'pdfkit/tests/helpers.js' {
  declare module.exports: $Exports<'pdfkit/tests/helpers'>;
}
declare module 'pdfkit/tests/images/bee.js' {
  declare module.exports: $Exports<'pdfkit/tests/images/bee'>;
}
declare module 'pdfkit/tests/pdfmake/absolute.spec.js' {
  declare module.exports: $Exports<'pdfkit/tests/pdfmake/absolute.spec'>;
}
declare module 'pdfkit/tests/pdfmake/background.spec.js' {
  declare module.exports: $Exports<'pdfkit/tests/pdfmake/background.spec'>;
}
declare module 'pdfkit/tests/pdfmake/basics.spec.js' {
  declare module.exports: $Exports<'pdfkit/tests/pdfmake/basics.spec'>;
}
declare module 'pdfkit/tests/pdfmake/columns_simple.spec.js' {
  declare module.exports: $Exports<'pdfkit/tests/pdfmake/columns_simple.spec'>;
}
declare module 'pdfkit/tests/pdfmake/images.spec.js' {
  declare module.exports: $Exports<'pdfkit/tests/pdfmake/images.spec'>;
}
declare module 'pdfkit/tests/pdfmake/lists.spec.js' {
  declare module.exports: $Exports<'pdfkit/tests/pdfmake/lists.spec'>;
}
declare module 'pdfkit/tests/pdfmake/page_references.spec.js' {
  declare module.exports: $Exports<'pdfkit/tests/pdfmake/page_references.spec'>;
}
declare module 'pdfkit/tests/pdfmake/qrcode.spec.js' {
  declare module.exports: $Exports<'pdfkit/tests/pdfmake/qrcode.spec'>;
}
declare module 'pdfkit/tests/pdfmake/tables.spec.js' {
  declare module.exports: $Exports<'pdfkit/tests/pdfmake/tables.spec'>;
}
declare module 'pdfkit/tests/pdfmake/text_decorations.spec.js' {
  declare module.exports: $Exports<'pdfkit/tests/pdfmake/text_decorations.spec'>;
}
declare module 'pdfkit/tests/pdfmake/toc.spec.js' {
  declare module.exports: $Exports<'pdfkit/tests/pdfmake/toc.spec'>;
}
declare module 'pdfkit/tests/pdfmake/watermark.spec.js' {
  declare module.exports: $Exports<'pdfkit/tests/pdfmake/watermark.spec'>;
}
declare module 'pdfkit/tests/text.spec.js' {
  declare module.exports: $Exports<'pdfkit/tests/text.spec'>;
}
declare module 'pdfkit/tests/unit/color.spec.js' {
  declare module.exports: $Exports<'pdfkit/tests/unit/color.spec'>;
}
declare module 'pdfkit/tests/vector.spec.js' {
  declare module.exports: $Exports<'pdfkit/tests/vector.spec'>;
}
