// flow-typed signature: ef9f032a97a7665f015fdd0f908f676e
// flow-typed version: <<STUB>>/rc-calendar_v^9.7.10/flow_v0.97.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'rc-calendar'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'rc-calendar' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'rc-calendar/dist/rc-calendar' {
  declare module.exports: any;
}

declare module 'rc-calendar/dist/rc-calendar.min' {
  declare module.exports: any;
}

declare module 'rc-calendar/es/Calendar' {
  declare module.exports: any;
}

declare module 'rc-calendar/es/calendar/CalendarFooter' {
  declare module.exports: any;
}

declare module 'rc-calendar/es/calendar/CalendarHeader' {
  declare module.exports: any;
}

declare module 'rc-calendar/es/calendar/OkButton' {
  declare module.exports: any;
}

declare module 'rc-calendar/es/calendar/TimePickerButton' {
  declare module.exports: any;
}

declare module 'rc-calendar/es/calendar/TodayButton' {
  declare module.exports: any;
}

declare module 'rc-calendar/es/date/DateConstants' {
  declare module.exports: any;
}

declare module 'rc-calendar/es/date/DateInput' {
  declare module.exports: any;
}

declare module 'rc-calendar/es/date/DateTable' {
  declare module.exports: any;
}

declare module 'rc-calendar/es/date/DateTBody' {
  declare module.exports: any;
}

declare module 'rc-calendar/es/date/DateTHead' {
  declare module.exports: any;
}

declare module 'rc-calendar/es/decade/DecadePanel' {
  declare module.exports: any;
}

declare module 'rc-calendar/es/full-calendar/CalendarHeader' {
  declare module.exports: any;
}

declare module 'rc-calendar/es/FullCalendar' {
  declare module.exports: any;
}

declare module 'rc-calendar/es/index' {
  declare module.exports: any;
}

declare module 'rc-calendar/es/locale/ar_EG' {
  declare module.exports: any;
}

declare module 'rc-calendar/es/locale/bg_BG' {
  declare module.exports: any;
}

declare module 'rc-calendar/es/locale/ca_ES' {
  declare module.exports: any;
}

declare module 'rc-calendar/es/locale/cs_CZ' {
  declare module.exports: any;
}

declare module 'rc-calendar/es/locale/da_DK' {
  declare module.exports: any;
}

declare module 'rc-calendar/es/locale/de_DE' {
  declare module.exports: any;
}

declare module 'rc-calendar/es/locale/el_GR' {
  declare module.exports: any;
}

declare module 'rc-calendar/es/locale/en_GB' {
  declare module.exports: any;
}

declare module 'rc-calendar/es/locale/en_US' {
  declare module.exports: any;
}

declare module 'rc-calendar/es/locale/es_ES' {
  declare module.exports: any;
}

declare module 'rc-calendar/es/locale/et_EE' {
  declare module.exports: any;
}

declare module 'rc-calendar/es/locale/fa_IR' {
  declare module.exports: any;
}

declare module 'rc-calendar/es/locale/fi_FI' {
  declare module.exports: any;
}

declare module 'rc-calendar/es/locale/fr_BE' {
  declare module.exports: any;
}

declare module 'rc-calendar/es/locale/fr_FR' {
  declare module.exports: any;
}

declare module 'rc-calendar/es/locale/he_IL' {
  declare module.exports: any;
}

declare module 'rc-calendar/es/locale/hu_HU' {
  declare module.exports: any;
}

declare module 'rc-calendar/es/locale/id_ID' {
  declare module.exports: any;
}

declare module 'rc-calendar/es/locale/is_IS' {
  declare module.exports: any;
}

declare module 'rc-calendar/es/locale/it_IT' {
  declare module.exports: any;
}

declare module 'rc-calendar/es/locale/ja_JP' {
  declare module.exports: any;
}

declare module 'rc-calendar/es/locale/ko_KR' {
  declare module.exports: any;
}

declare module 'rc-calendar/es/locale/ku_IQ' {
  declare module.exports: any;
}

declare module 'rc-calendar/es/locale/mm_MM' {
  declare module.exports: any;
}

declare module 'rc-calendar/es/locale/mn_MN' {
  declare module.exports: any;
}

declare module 'rc-calendar/es/locale/nb_NO' {
  declare module.exports: any;
}

declare module 'rc-calendar/es/locale/nl_BE' {
  declare module.exports: any;
}

declare module 'rc-calendar/es/locale/nl_NL' {
  declare module.exports: any;
}

declare module 'rc-calendar/es/locale/pl_PL' {
  declare module.exports: any;
}

declare module 'rc-calendar/es/locale/pt_BR' {
  declare module.exports: any;
}

declare module 'rc-calendar/es/locale/pt_PT' {
  declare module.exports: any;
}

declare module 'rc-calendar/es/locale/ru_RU' {
  declare module.exports: any;
}

declare module 'rc-calendar/es/locale/sk_SK' {
  declare module.exports: any;
}

declare module 'rc-calendar/es/locale/sl_SI' {
  declare module.exports: any;
}

declare module 'rc-calendar/es/locale/sr_RS' {
  declare module.exports: any;
}

declare module 'rc-calendar/es/locale/sv_SE' {
  declare module.exports: any;
}

declare module 'rc-calendar/es/locale/th_TH' {
  declare module.exports: any;
}

declare module 'rc-calendar/es/locale/tr_TR' {
  declare module.exports: any;
}

declare module 'rc-calendar/es/locale/ug_CN' {
  declare module.exports: any;
}

declare module 'rc-calendar/es/locale/uk_UA' {
  declare module.exports: any;
}

declare module 'rc-calendar/es/locale/vi_VN' {
  declare module.exports: any;
}

declare module 'rc-calendar/es/locale/zh_CN' {
  declare module.exports: any;
}

declare module 'rc-calendar/es/locale/zh_TW' {
  declare module.exports: any;
}

declare module 'rc-calendar/es/mixin/CalendarMixin' {
  declare module.exports: any;
}

declare module 'rc-calendar/es/mixin/CommonMixin' {
  declare module.exports: any;
}

declare module 'rc-calendar/es/month/MonthPanel' {
  declare module.exports: any;
}

declare module 'rc-calendar/es/month/MonthTable' {
  declare module.exports: any;
}

declare module 'rc-calendar/es/MonthCalendar' {
  declare module.exports: any;
}

declare module 'rc-calendar/es/Picker' {
  declare module.exports: any;
}

declare module 'rc-calendar/es/picker/placements' {
  declare module.exports: any;
}

declare module 'rc-calendar/es/range-calendar/CalendarPart' {
  declare module.exports: any;
}

declare module 'rc-calendar/es/RangeCalendar' {
  declare module.exports: any;
}

declare module 'rc-calendar/es/util/index' {
  declare module.exports: any;
}

declare module 'rc-calendar/es/util/toTime' {
  declare module.exports: any;
}

declare module 'rc-calendar/es/year/YearPanel' {
  declare module.exports: any;
}

declare module 'rc-calendar/lib/Calendar' {
  declare module.exports: any;
}

declare module 'rc-calendar/lib/calendar/CalendarFooter' {
  declare module.exports: any;
}

declare module 'rc-calendar/lib/calendar/CalendarHeader' {
  declare module.exports: any;
}

declare module 'rc-calendar/lib/calendar/OkButton' {
  declare module.exports: any;
}

declare module 'rc-calendar/lib/calendar/TimePickerButton' {
  declare module.exports: any;
}

declare module 'rc-calendar/lib/calendar/TodayButton' {
  declare module.exports: any;
}

declare module 'rc-calendar/lib/date/DateConstants' {
  declare module.exports: any;
}

declare module 'rc-calendar/lib/date/DateInput' {
  declare module.exports: any;
}

declare module 'rc-calendar/lib/date/DateTable' {
  declare module.exports: any;
}

declare module 'rc-calendar/lib/date/DateTBody' {
  declare module.exports: any;
}

declare module 'rc-calendar/lib/date/DateTHead' {
  declare module.exports: any;
}

declare module 'rc-calendar/lib/decade/DecadePanel' {
  declare module.exports: any;
}

declare module 'rc-calendar/lib/full-calendar/CalendarHeader' {
  declare module.exports: any;
}

declare module 'rc-calendar/lib/FullCalendar' {
  declare module.exports: any;
}

declare module 'rc-calendar/lib/index' {
  declare module.exports: any;
}

declare module 'rc-calendar/lib/locale/ar_EG' {
  declare module.exports: any;
}

declare module 'rc-calendar/lib/locale/bg_BG' {
  declare module.exports: any;
}

declare module 'rc-calendar/lib/locale/ca_ES' {
  declare module.exports: any;
}

declare module 'rc-calendar/lib/locale/cs_CZ' {
  declare module.exports: any;
}

declare module 'rc-calendar/lib/locale/da_DK' {
  declare module.exports: any;
}

declare module 'rc-calendar/lib/locale/de_DE' {
  declare module.exports: any;
}

declare module 'rc-calendar/lib/locale/el_GR' {
  declare module.exports: any;
}

declare module 'rc-calendar/lib/locale/en_GB' {
  declare module.exports: any;
}

declare module 'rc-calendar/lib/locale/en_US' {
  declare module.exports: any;
}

declare module 'rc-calendar/lib/locale/es_ES' {
  declare module.exports: any;
}

declare module 'rc-calendar/lib/locale/et_EE' {
  declare module.exports: any;
}

declare module 'rc-calendar/lib/locale/fa_IR' {
  declare module.exports: any;
}

declare module 'rc-calendar/lib/locale/fi_FI' {
  declare module.exports: any;
}

declare module 'rc-calendar/lib/locale/fr_BE' {
  declare module.exports: any;
}

declare module 'rc-calendar/lib/locale/fr_FR' {
  declare module.exports: any;
}

declare module 'rc-calendar/lib/locale/he_IL' {
  declare module.exports: any;
}

declare module 'rc-calendar/lib/locale/hu_HU' {
  declare module.exports: any;
}

declare module 'rc-calendar/lib/locale/id_ID' {
  declare module.exports: any;
}

declare module 'rc-calendar/lib/locale/is_IS' {
  declare module.exports: any;
}

declare module 'rc-calendar/lib/locale/it_IT' {
  declare module.exports: any;
}

declare module 'rc-calendar/lib/locale/ja_JP' {
  declare module.exports: any;
}

declare module 'rc-calendar/lib/locale/ko_KR' {
  declare module.exports: any;
}

declare module 'rc-calendar/lib/locale/ku_IQ' {
  declare module.exports: any;
}

declare module 'rc-calendar/lib/locale/mm_MM' {
  declare module.exports: any;
}

declare module 'rc-calendar/lib/locale/mn_MN' {
  declare module.exports: any;
}

declare module 'rc-calendar/lib/locale/nb_NO' {
  declare module.exports: any;
}

declare module 'rc-calendar/lib/locale/nl_BE' {
  declare module.exports: any;
}

declare module 'rc-calendar/lib/locale/nl_NL' {
  declare module.exports: any;
}

declare module 'rc-calendar/lib/locale/pl_PL' {
  declare module.exports: any;
}

declare module 'rc-calendar/lib/locale/pt_BR' {
  declare module.exports: any;
}

declare module 'rc-calendar/lib/locale/pt_PT' {
  declare module.exports: any;
}

declare module 'rc-calendar/lib/locale/ru_RU' {
  declare module.exports: any;
}

declare module 'rc-calendar/lib/locale/sk_SK' {
  declare module.exports: any;
}

declare module 'rc-calendar/lib/locale/sl_SI' {
  declare module.exports: any;
}

declare module 'rc-calendar/lib/locale/sr_RS' {
  declare module.exports: any;
}

declare module 'rc-calendar/lib/locale/sv_SE' {
  declare module.exports: any;
}

declare module 'rc-calendar/lib/locale/th_TH' {
  declare module.exports: any;
}

declare module 'rc-calendar/lib/locale/tr_TR' {
  declare module.exports: any;
}

declare module 'rc-calendar/lib/locale/ug_CN' {
  declare module.exports: any;
}

declare module 'rc-calendar/lib/locale/uk_UA' {
  declare module.exports: any;
}

declare module 'rc-calendar/lib/locale/vi_VN' {
  declare module.exports: any;
}

declare module 'rc-calendar/lib/locale/zh_CN' {
  declare module.exports: any;
}

declare module 'rc-calendar/lib/locale/zh_TW' {
  declare module.exports: any;
}

declare module 'rc-calendar/lib/mixin/CalendarMixin' {
  declare module.exports: any;
}

declare module 'rc-calendar/lib/mixin/CommonMixin' {
  declare module.exports: any;
}

declare module 'rc-calendar/lib/month/MonthPanel' {
  declare module.exports: any;
}

declare module 'rc-calendar/lib/month/MonthTable' {
  declare module.exports: any;
}

declare module 'rc-calendar/lib/MonthCalendar' {
  declare module.exports: any;
}

declare module 'rc-calendar/lib/Picker' {
  declare module.exports: any;
}

declare module 'rc-calendar/lib/picker/placements' {
  declare module.exports: any;
}

declare module 'rc-calendar/lib/range-calendar/CalendarPart' {
  declare module.exports: any;
}

declare module 'rc-calendar/lib/RangeCalendar' {
  declare module.exports: any;
}

declare module 'rc-calendar/lib/util/index' {
  declare module.exports: any;
}

declare module 'rc-calendar/lib/util/toTime' {
  declare module.exports: any;
}

declare module 'rc-calendar/lib/year/YearPanel' {
  declare module.exports: any;
}

// Filename aliases
declare module 'rc-calendar/dist/rc-calendar.js' {
  declare module.exports: $Exports<'rc-calendar/dist/rc-calendar'>;
}
declare module 'rc-calendar/dist/rc-calendar.min.js' {
  declare module.exports: $Exports<'rc-calendar/dist/rc-calendar.min'>;
}
declare module 'rc-calendar/es/Calendar.js' {
  declare module.exports: $Exports<'rc-calendar/es/Calendar'>;
}
declare module 'rc-calendar/es/calendar/CalendarFooter.js' {
  declare module.exports: $Exports<'rc-calendar/es/calendar/CalendarFooter'>;
}
declare module 'rc-calendar/es/calendar/CalendarHeader.js' {
  declare module.exports: $Exports<'rc-calendar/es/calendar/CalendarHeader'>;
}
declare module 'rc-calendar/es/calendar/OkButton.js' {
  declare module.exports: $Exports<'rc-calendar/es/calendar/OkButton'>;
}
declare module 'rc-calendar/es/calendar/TimePickerButton.js' {
  declare module.exports: $Exports<'rc-calendar/es/calendar/TimePickerButton'>;
}
declare module 'rc-calendar/es/calendar/TodayButton.js' {
  declare module.exports: $Exports<'rc-calendar/es/calendar/TodayButton'>;
}
declare module 'rc-calendar/es/date/DateConstants.js' {
  declare module.exports: $Exports<'rc-calendar/es/date/DateConstants'>;
}
declare module 'rc-calendar/es/date/DateInput.js' {
  declare module.exports: $Exports<'rc-calendar/es/date/DateInput'>;
}
declare module 'rc-calendar/es/date/DateTable.js' {
  declare module.exports: $Exports<'rc-calendar/es/date/DateTable'>;
}
declare module 'rc-calendar/es/date/DateTBody.js' {
  declare module.exports: $Exports<'rc-calendar/es/date/DateTBody'>;
}
declare module 'rc-calendar/es/date/DateTHead.js' {
  declare module.exports: $Exports<'rc-calendar/es/date/DateTHead'>;
}
declare module 'rc-calendar/es/decade/DecadePanel.js' {
  declare module.exports: $Exports<'rc-calendar/es/decade/DecadePanel'>;
}
declare module 'rc-calendar/es/full-calendar/CalendarHeader.js' {
  declare module.exports: $Exports<'rc-calendar/es/full-calendar/CalendarHeader'>;
}
declare module 'rc-calendar/es/FullCalendar.js' {
  declare module.exports: $Exports<'rc-calendar/es/FullCalendar'>;
}
declare module 'rc-calendar/es/index.js' {
  declare module.exports: $Exports<'rc-calendar/es/index'>;
}
declare module 'rc-calendar/es/locale/ar_EG.js' {
  declare module.exports: $Exports<'rc-calendar/es/locale/ar_EG'>;
}
declare module 'rc-calendar/es/locale/bg_BG.js' {
  declare module.exports: $Exports<'rc-calendar/es/locale/bg_BG'>;
}
declare module 'rc-calendar/es/locale/ca_ES.js' {
  declare module.exports: $Exports<'rc-calendar/es/locale/ca_ES'>;
}
declare module 'rc-calendar/es/locale/cs_CZ.js' {
  declare module.exports: $Exports<'rc-calendar/es/locale/cs_CZ'>;
}
declare module 'rc-calendar/es/locale/da_DK.js' {
  declare module.exports: $Exports<'rc-calendar/es/locale/da_DK'>;
}
declare module 'rc-calendar/es/locale/de_DE.js' {
  declare module.exports: $Exports<'rc-calendar/es/locale/de_DE'>;
}
declare module 'rc-calendar/es/locale/el_GR.js' {
  declare module.exports: $Exports<'rc-calendar/es/locale/el_GR'>;
}
declare module 'rc-calendar/es/locale/en_GB.js' {
  declare module.exports: $Exports<'rc-calendar/es/locale/en_GB'>;
}
declare module 'rc-calendar/es/locale/en_US.js' {
  declare module.exports: $Exports<'rc-calendar/es/locale/en_US'>;
}
declare module 'rc-calendar/es/locale/es_ES.js' {
  declare module.exports: $Exports<'rc-calendar/es/locale/es_ES'>;
}
declare module 'rc-calendar/es/locale/et_EE.js' {
  declare module.exports: $Exports<'rc-calendar/es/locale/et_EE'>;
}
declare module 'rc-calendar/es/locale/fa_IR.js' {
  declare module.exports: $Exports<'rc-calendar/es/locale/fa_IR'>;
}
declare module 'rc-calendar/es/locale/fi_FI.js' {
  declare module.exports: $Exports<'rc-calendar/es/locale/fi_FI'>;
}
declare module 'rc-calendar/es/locale/fr_BE.js' {
  declare module.exports: $Exports<'rc-calendar/es/locale/fr_BE'>;
}
declare module 'rc-calendar/es/locale/fr_FR.js' {
  declare module.exports: $Exports<'rc-calendar/es/locale/fr_FR'>;
}
declare module 'rc-calendar/es/locale/he_IL.js' {
  declare module.exports: $Exports<'rc-calendar/es/locale/he_IL'>;
}
declare module 'rc-calendar/es/locale/hu_HU.js' {
  declare module.exports: $Exports<'rc-calendar/es/locale/hu_HU'>;
}
declare module 'rc-calendar/es/locale/id_ID.js' {
  declare module.exports: $Exports<'rc-calendar/es/locale/id_ID'>;
}
declare module 'rc-calendar/es/locale/is_IS.js' {
  declare module.exports: $Exports<'rc-calendar/es/locale/is_IS'>;
}
declare module 'rc-calendar/es/locale/it_IT.js' {
  declare module.exports: $Exports<'rc-calendar/es/locale/it_IT'>;
}
declare module 'rc-calendar/es/locale/ja_JP.js' {
  declare module.exports: $Exports<'rc-calendar/es/locale/ja_JP'>;
}
declare module 'rc-calendar/es/locale/ko_KR.js' {
  declare module.exports: $Exports<'rc-calendar/es/locale/ko_KR'>;
}
declare module 'rc-calendar/es/locale/ku_IQ.js' {
  declare module.exports: $Exports<'rc-calendar/es/locale/ku_IQ'>;
}
declare module 'rc-calendar/es/locale/mm_MM.js' {
  declare module.exports: $Exports<'rc-calendar/es/locale/mm_MM'>;
}
declare module 'rc-calendar/es/locale/mn_MN.js' {
  declare module.exports: $Exports<'rc-calendar/es/locale/mn_MN'>;
}
declare module 'rc-calendar/es/locale/nb_NO.js' {
  declare module.exports: $Exports<'rc-calendar/es/locale/nb_NO'>;
}
declare module 'rc-calendar/es/locale/nl_BE.js' {
  declare module.exports: $Exports<'rc-calendar/es/locale/nl_BE'>;
}
declare module 'rc-calendar/es/locale/nl_NL.js' {
  declare module.exports: $Exports<'rc-calendar/es/locale/nl_NL'>;
}
declare module 'rc-calendar/es/locale/pl_PL.js' {
  declare module.exports: $Exports<'rc-calendar/es/locale/pl_PL'>;
}
declare module 'rc-calendar/es/locale/pt_BR.js' {
  declare module.exports: $Exports<'rc-calendar/es/locale/pt_BR'>;
}
declare module 'rc-calendar/es/locale/pt_PT.js' {
  declare module.exports: $Exports<'rc-calendar/es/locale/pt_PT'>;
}
declare module 'rc-calendar/es/locale/ru_RU.js' {
  declare module.exports: $Exports<'rc-calendar/es/locale/ru_RU'>;
}
declare module 'rc-calendar/es/locale/sk_SK.js' {
  declare module.exports: $Exports<'rc-calendar/es/locale/sk_SK'>;
}
declare module 'rc-calendar/es/locale/sl_SI.js' {
  declare module.exports: $Exports<'rc-calendar/es/locale/sl_SI'>;
}
declare module 'rc-calendar/es/locale/sr_RS.js' {
  declare module.exports: $Exports<'rc-calendar/es/locale/sr_RS'>;
}
declare module 'rc-calendar/es/locale/sv_SE.js' {
  declare module.exports: $Exports<'rc-calendar/es/locale/sv_SE'>;
}
declare module 'rc-calendar/es/locale/th_TH.js' {
  declare module.exports: $Exports<'rc-calendar/es/locale/th_TH'>;
}
declare module 'rc-calendar/es/locale/tr_TR.js' {
  declare module.exports: $Exports<'rc-calendar/es/locale/tr_TR'>;
}
declare module 'rc-calendar/es/locale/ug_CN.js' {
  declare module.exports: $Exports<'rc-calendar/es/locale/ug_CN'>;
}
declare module 'rc-calendar/es/locale/uk_UA.js' {
  declare module.exports: $Exports<'rc-calendar/es/locale/uk_UA'>;
}
declare module 'rc-calendar/es/locale/vi_VN.js' {
  declare module.exports: $Exports<'rc-calendar/es/locale/vi_VN'>;
}
declare module 'rc-calendar/es/locale/zh_CN.js' {
  declare module.exports: $Exports<'rc-calendar/es/locale/zh_CN'>;
}
declare module 'rc-calendar/es/locale/zh_TW.js' {
  declare module.exports: $Exports<'rc-calendar/es/locale/zh_TW'>;
}
declare module 'rc-calendar/es/mixin/CalendarMixin.js' {
  declare module.exports: $Exports<'rc-calendar/es/mixin/CalendarMixin'>;
}
declare module 'rc-calendar/es/mixin/CommonMixin.js' {
  declare module.exports: $Exports<'rc-calendar/es/mixin/CommonMixin'>;
}
declare module 'rc-calendar/es/month/MonthPanel.js' {
  declare module.exports: $Exports<'rc-calendar/es/month/MonthPanel'>;
}
declare module 'rc-calendar/es/month/MonthTable.js' {
  declare module.exports: $Exports<'rc-calendar/es/month/MonthTable'>;
}
declare module 'rc-calendar/es/MonthCalendar.js' {
  declare module.exports: $Exports<'rc-calendar/es/MonthCalendar'>;
}
declare module 'rc-calendar/es/Picker.js' {
  declare module.exports: $Exports<'rc-calendar/es/Picker'>;
}
declare module 'rc-calendar/es/picker/placements.js' {
  declare module.exports: $Exports<'rc-calendar/es/picker/placements'>;
}
declare module 'rc-calendar/es/range-calendar/CalendarPart.js' {
  declare module.exports: $Exports<'rc-calendar/es/range-calendar/CalendarPart'>;
}
declare module 'rc-calendar/es/RangeCalendar.js' {
  declare module.exports: $Exports<'rc-calendar/es/RangeCalendar'>;
}
declare module 'rc-calendar/es/util/index.js' {
  declare module.exports: $Exports<'rc-calendar/es/util/index'>;
}
declare module 'rc-calendar/es/util/toTime.js' {
  declare module.exports: $Exports<'rc-calendar/es/util/toTime'>;
}
declare module 'rc-calendar/es/year/YearPanel.js' {
  declare module.exports: $Exports<'rc-calendar/es/year/YearPanel'>;
}
declare module 'rc-calendar/lib/Calendar.js' {
  declare module.exports: $Exports<'rc-calendar/lib/Calendar'>;
}
declare module 'rc-calendar/lib/calendar/CalendarFooter.js' {
  declare module.exports: $Exports<'rc-calendar/lib/calendar/CalendarFooter'>;
}
declare module 'rc-calendar/lib/calendar/CalendarHeader.js' {
  declare module.exports: $Exports<'rc-calendar/lib/calendar/CalendarHeader'>;
}
declare module 'rc-calendar/lib/calendar/OkButton.js' {
  declare module.exports: $Exports<'rc-calendar/lib/calendar/OkButton'>;
}
declare module 'rc-calendar/lib/calendar/TimePickerButton.js' {
  declare module.exports: $Exports<'rc-calendar/lib/calendar/TimePickerButton'>;
}
declare module 'rc-calendar/lib/calendar/TodayButton.js' {
  declare module.exports: $Exports<'rc-calendar/lib/calendar/TodayButton'>;
}
declare module 'rc-calendar/lib/date/DateConstants.js' {
  declare module.exports: $Exports<'rc-calendar/lib/date/DateConstants'>;
}
declare module 'rc-calendar/lib/date/DateInput.js' {
  declare module.exports: $Exports<'rc-calendar/lib/date/DateInput'>;
}
declare module 'rc-calendar/lib/date/DateTable.js' {
  declare module.exports: $Exports<'rc-calendar/lib/date/DateTable'>;
}
declare module 'rc-calendar/lib/date/DateTBody.js' {
  declare module.exports: $Exports<'rc-calendar/lib/date/DateTBody'>;
}
declare module 'rc-calendar/lib/date/DateTHead.js' {
  declare module.exports: $Exports<'rc-calendar/lib/date/DateTHead'>;
}
declare module 'rc-calendar/lib/decade/DecadePanel.js' {
  declare module.exports: $Exports<'rc-calendar/lib/decade/DecadePanel'>;
}
declare module 'rc-calendar/lib/full-calendar/CalendarHeader.js' {
  declare module.exports: $Exports<'rc-calendar/lib/full-calendar/CalendarHeader'>;
}
declare module 'rc-calendar/lib/FullCalendar.js' {
  declare module.exports: $Exports<'rc-calendar/lib/FullCalendar'>;
}
declare module 'rc-calendar/lib/index.js' {
  declare module.exports: $Exports<'rc-calendar/lib/index'>;
}
declare module 'rc-calendar/lib/locale/ar_EG.js' {
  declare module.exports: $Exports<'rc-calendar/lib/locale/ar_EG'>;
}
declare module 'rc-calendar/lib/locale/bg_BG.js' {
  declare module.exports: $Exports<'rc-calendar/lib/locale/bg_BG'>;
}
declare module 'rc-calendar/lib/locale/ca_ES.js' {
  declare module.exports: $Exports<'rc-calendar/lib/locale/ca_ES'>;
}
declare module 'rc-calendar/lib/locale/cs_CZ.js' {
  declare module.exports: $Exports<'rc-calendar/lib/locale/cs_CZ'>;
}
declare module 'rc-calendar/lib/locale/da_DK.js' {
  declare module.exports: $Exports<'rc-calendar/lib/locale/da_DK'>;
}
declare module 'rc-calendar/lib/locale/de_DE.js' {
  declare module.exports: $Exports<'rc-calendar/lib/locale/de_DE'>;
}
declare module 'rc-calendar/lib/locale/el_GR.js' {
  declare module.exports: $Exports<'rc-calendar/lib/locale/el_GR'>;
}
declare module 'rc-calendar/lib/locale/en_GB.js' {
  declare module.exports: $Exports<'rc-calendar/lib/locale/en_GB'>;
}
declare module 'rc-calendar/lib/locale/en_US.js' {
  declare module.exports: $Exports<'rc-calendar/lib/locale/en_US'>;
}
declare module 'rc-calendar/lib/locale/es_ES.js' {
  declare module.exports: $Exports<'rc-calendar/lib/locale/es_ES'>;
}
declare module 'rc-calendar/lib/locale/et_EE.js' {
  declare module.exports: $Exports<'rc-calendar/lib/locale/et_EE'>;
}
declare module 'rc-calendar/lib/locale/fa_IR.js' {
  declare module.exports: $Exports<'rc-calendar/lib/locale/fa_IR'>;
}
declare module 'rc-calendar/lib/locale/fi_FI.js' {
  declare module.exports: $Exports<'rc-calendar/lib/locale/fi_FI'>;
}
declare module 'rc-calendar/lib/locale/fr_BE.js' {
  declare module.exports: $Exports<'rc-calendar/lib/locale/fr_BE'>;
}
declare module 'rc-calendar/lib/locale/fr_FR.js' {
  declare module.exports: $Exports<'rc-calendar/lib/locale/fr_FR'>;
}
declare module 'rc-calendar/lib/locale/he_IL.js' {
  declare module.exports: $Exports<'rc-calendar/lib/locale/he_IL'>;
}
declare module 'rc-calendar/lib/locale/hu_HU.js' {
  declare module.exports: $Exports<'rc-calendar/lib/locale/hu_HU'>;
}
declare module 'rc-calendar/lib/locale/id_ID.js' {
  declare module.exports: $Exports<'rc-calendar/lib/locale/id_ID'>;
}
declare module 'rc-calendar/lib/locale/is_IS.js' {
  declare module.exports: $Exports<'rc-calendar/lib/locale/is_IS'>;
}
declare module 'rc-calendar/lib/locale/it_IT.js' {
  declare module.exports: $Exports<'rc-calendar/lib/locale/it_IT'>;
}
declare module 'rc-calendar/lib/locale/ja_JP.js' {
  declare module.exports: $Exports<'rc-calendar/lib/locale/ja_JP'>;
}
declare module 'rc-calendar/lib/locale/ko_KR.js' {
  declare module.exports: $Exports<'rc-calendar/lib/locale/ko_KR'>;
}
declare module 'rc-calendar/lib/locale/ku_IQ.js' {
  declare module.exports: $Exports<'rc-calendar/lib/locale/ku_IQ'>;
}
declare module 'rc-calendar/lib/locale/mm_MM.js' {
  declare module.exports: $Exports<'rc-calendar/lib/locale/mm_MM'>;
}
declare module 'rc-calendar/lib/locale/mn_MN.js' {
  declare module.exports: $Exports<'rc-calendar/lib/locale/mn_MN'>;
}
declare module 'rc-calendar/lib/locale/nb_NO.js' {
  declare module.exports: $Exports<'rc-calendar/lib/locale/nb_NO'>;
}
declare module 'rc-calendar/lib/locale/nl_BE.js' {
  declare module.exports: $Exports<'rc-calendar/lib/locale/nl_BE'>;
}
declare module 'rc-calendar/lib/locale/nl_NL.js' {
  declare module.exports: $Exports<'rc-calendar/lib/locale/nl_NL'>;
}
declare module 'rc-calendar/lib/locale/pl_PL.js' {
  declare module.exports: $Exports<'rc-calendar/lib/locale/pl_PL'>;
}
declare module 'rc-calendar/lib/locale/pt_BR.js' {
  declare module.exports: $Exports<'rc-calendar/lib/locale/pt_BR'>;
}
declare module 'rc-calendar/lib/locale/pt_PT.js' {
  declare module.exports: $Exports<'rc-calendar/lib/locale/pt_PT'>;
}
declare module 'rc-calendar/lib/locale/ru_RU.js' {
  declare module.exports: $Exports<'rc-calendar/lib/locale/ru_RU'>;
}
declare module 'rc-calendar/lib/locale/sk_SK.js' {
  declare module.exports: $Exports<'rc-calendar/lib/locale/sk_SK'>;
}
declare module 'rc-calendar/lib/locale/sl_SI.js' {
  declare module.exports: $Exports<'rc-calendar/lib/locale/sl_SI'>;
}
declare module 'rc-calendar/lib/locale/sr_RS.js' {
  declare module.exports: $Exports<'rc-calendar/lib/locale/sr_RS'>;
}
declare module 'rc-calendar/lib/locale/sv_SE.js' {
  declare module.exports: $Exports<'rc-calendar/lib/locale/sv_SE'>;
}
declare module 'rc-calendar/lib/locale/th_TH.js' {
  declare module.exports: $Exports<'rc-calendar/lib/locale/th_TH'>;
}
declare module 'rc-calendar/lib/locale/tr_TR.js' {
  declare module.exports: $Exports<'rc-calendar/lib/locale/tr_TR'>;
}
declare module 'rc-calendar/lib/locale/ug_CN.js' {
  declare module.exports: $Exports<'rc-calendar/lib/locale/ug_CN'>;
}
declare module 'rc-calendar/lib/locale/uk_UA.js' {
  declare module.exports: $Exports<'rc-calendar/lib/locale/uk_UA'>;
}
declare module 'rc-calendar/lib/locale/vi_VN.js' {
  declare module.exports: $Exports<'rc-calendar/lib/locale/vi_VN'>;
}
declare module 'rc-calendar/lib/locale/zh_CN.js' {
  declare module.exports: $Exports<'rc-calendar/lib/locale/zh_CN'>;
}
declare module 'rc-calendar/lib/locale/zh_TW.js' {
  declare module.exports: $Exports<'rc-calendar/lib/locale/zh_TW'>;
}
declare module 'rc-calendar/lib/mixin/CalendarMixin.js' {
  declare module.exports: $Exports<'rc-calendar/lib/mixin/CalendarMixin'>;
}
declare module 'rc-calendar/lib/mixin/CommonMixin.js' {
  declare module.exports: $Exports<'rc-calendar/lib/mixin/CommonMixin'>;
}
declare module 'rc-calendar/lib/month/MonthPanel.js' {
  declare module.exports: $Exports<'rc-calendar/lib/month/MonthPanel'>;
}
declare module 'rc-calendar/lib/month/MonthTable.js' {
  declare module.exports: $Exports<'rc-calendar/lib/month/MonthTable'>;
}
declare module 'rc-calendar/lib/MonthCalendar.js' {
  declare module.exports: $Exports<'rc-calendar/lib/MonthCalendar'>;
}
declare module 'rc-calendar/lib/Picker.js' {
  declare module.exports: $Exports<'rc-calendar/lib/Picker'>;
}
declare module 'rc-calendar/lib/picker/placements.js' {
  declare module.exports: $Exports<'rc-calendar/lib/picker/placements'>;
}
declare module 'rc-calendar/lib/range-calendar/CalendarPart.js' {
  declare module.exports: $Exports<'rc-calendar/lib/range-calendar/CalendarPart'>;
}
declare module 'rc-calendar/lib/RangeCalendar.js' {
  declare module.exports: $Exports<'rc-calendar/lib/RangeCalendar'>;
}
declare module 'rc-calendar/lib/util/index.js' {
  declare module.exports: $Exports<'rc-calendar/lib/util/index'>;
}
declare module 'rc-calendar/lib/util/toTime.js' {
  declare module.exports: $Exports<'rc-calendar/lib/util/toTime'>;
}
declare module 'rc-calendar/lib/year/YearPanel.js' {
  declare module.exports: $Exports<'rc-calendar/lib/year/YearPanel'>;
}
