// flow-typed signature: 13e1259914a5b0c8f917f3a48a9daf6e
// flow-typed version: <<STUB>>/react-svg-donut-chart_v^1.0.0/flow_v0.97.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'react-svg-donut-chart'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'react-svg-donut-chart' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'react-svg-donut-chart/es/constants' {
  declare module.exports: any;
}

declare module 'react-svg-donut-chart/es/index' {
  declare module.exports: any;
}

declare module 'react-svg-donut-chart/es/Segment/index' {
  declare module.exports: any;
}

declare module 'react-svg-donut-chart/lib/constants' {
  declare module.exports: any;
}

declare module 'react-svg-donut-chart/lib/index' {
  declare module.exports: any;
}

declare module 'react-svg-donut-chart/lib/Segment/index' {
  declare module.exports: any;
}

declare module 'react-svg-donut-chart/umd/react-svg-donut-chart' {
  declare module.exports: any;
}

// Filename aliases
declare module 'react-svg-donut-chart/es/constants.js' {
  declare module.exports: $Exports<'react-svg-donut-chart/es/constants'>;
}
declare module 'react-svg-donut-chart/es/index.js' {
  declare module.exports: $Exports<'react-svg-donut-chart/es/index'>;
}
declare module 'react-svg-donut-chart/es/Segment/index.js' {
  declare module.exports: $Exports<'react-svg-donut-chart/es/Segment/index'>;
}
declare module 'react-svg-donut-chart/lib/constants.js' {
  declare module.exports: $Exports<'react-svg-donut-chart/lib/constants'>;
}
declare module 'react-svg-donut-chart/lib/index.js' {
  declare module.exports: $Exports<'react-svg-donut-chart/lib/index'>;
}
declare module 'react-svg-donut-chart/lib/Segment/index.js' {
  declare module.exports: $Exports<'react-svg-donut-chart/lib/Segment/index'>;
}
declare module 'react-svg-donut-chart/umd/react-svg-donut-chart.js' {
  declare module.exports: $Exports<'react-svg-donut-chart/umd/react-svg-donut-chart'>;
}
