// flow-typed signature: d0644c118ba4c558617d608cc93b3fca
// flow-typed version: <<STUB>>/react-user-avatar_v^1.10.0/flow_v0.76.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'react-user-avatar'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'react-user-avatar' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'react-user-avatar/user-avatar' {
  declare module.exports: any;
}

// Filename aliases
declare module 'react-user-avatar/index' {
  declare module.exports: $Exports<'react-user-avatar'>;
}
declare module 'react-user-avatar/index.js' {
  declare module.exports: $Exports<'react-user-avatar'>;
}
declare module 'react-user-avatar/user-avatar.js' {
  declare module.exports: $Exports<'react-user-avatar/user-avatar'>;
}
