// flow-typed signature: 7f7b825b9e06a0bfcf0aa259d84278d3
// flow-typed version: <<STUB>>/react-contenteditable_v^3.1.1/flow_v0.97.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'react-contenteditable'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'react-contenteditable' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'react-contenteditable/lib/react-contenteditable' {
  declare module.exports: any;
}

// Filename aliases
declare module 'react-contenteditable/lib/react-contenteditable.js' {
  declare module.exports: $Exports<'react-contenteditable/lib/react-contenteditable'>;
}
