// flow-typed signature: e54607efb2d40bac099642c777d44b9c
// flow-typed version: <<STUB>>/react-intercom_v^1.0.15/flow_v0.97.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'react-intercom'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'react-intercom' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'react-intercom/lib/index' {
  declare module.exports: any;
}

declare module 'react-intercom/src/index' {
  declare module.exports: any;
}

// Filename aliases
declare module 'react-intercom/lib/index.js' {
  declare module.exports: $Exports<'react-intercom/lib/index'>;
}
declare module 'react-intercom/src/index.js' {
  declare module.exports: $Exports<'react-intercom/src/index'>;
}
