// flow-typed signature: 251a70b532f3acd0e8c9403859c0f8a6
// flow-typed version: <<STUB>>/substyle_v^6.2.1/flow_v0.77.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'substyle'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'substyle' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'substyle/lib/coerceSelection' {
  declare module.exports: any;
}

declare module 'substyle/lib/createSubstyle' {
  declare module.exports: any;
}

declare module 'substyle/lib/defaultPropsDecorator' {
  declare module.exports: any;
}

declare module 'substyle/lib/defaultStyle' {
  declare module.exports: any;
}

declare module 'substyle/lib/EnhancerProvider' {
  declare module.exports: any;
}

declare module 'substyle/lib/filterKeys' {
  declare module.exports: any;
}

declare module 'substyle/lib/index' {
  declare module.exports: any;
}

declare module 'substyle/lib/memoize' {
  declare module.exports: any;
}

declare module 'substyle/lib/pickStyles' {
  declare module.exports: any;
}

declare module 'substyle/lib/types' {
  declare module.exports: any;
}

// Filename aliases
declare module 'substyle/lib/coerceSelection.js' {
  declare module.exports: $Exports<'substyle/lib/coerceSelection'>;
}
declare module 'substyle/lib/createSubstyle.js' {
  declare module.exports: $Exports<'substyle/lib/createSubstyle'>;
}
declare module 'substyle/lib/defaultPropsDecorator.js' {
  declare module.exports: $Exports<'substyle/lib/defaultPropsDecorator'>;
}
declare module 'substyle/lib/defaultStyle.js' {
  declare module.exports: $Exports<'substyle/lib/defaultStyle'>;
}
declare module 'substyle/lib/EnhancerProvider.js' {
  declare module.exports: $Exports<'substyle/lib/EnhancerProvider'>;
}
declare module 'substyle/lib/filterKeys.js' {
  declare module.exports: $Exports<'substyle/lib/filterKeys'>;
}
declare module 'substyle/lib/index.js' {
  declare module.exports: $Exports<'substyle/lib/index'>;
}
declare module 'substyle/lib/memoize.js' {
  declare module.exports: $Exports<'substyle/lib/memoize'>;
}
declare module 'substyle/lib/pickStyles.js' {
  declare module.exports: $Exports<'substyle/lib/pickStyles'>;
}
declare module 'substyle/lib/types.js' {
  declare module.exports: $Exports<'substyle/lib/types'>;
}
