/* eslint-disable */
export default `
Effective date: January 20, 2018

This Customer Agreement (the “Agreement”) is between you (“Customer”, “you”, or “your”) and ProductionCliq, LLC, a Texas limited liability company (“ProCliq” or “we”, “our”, or “us”). If you are using the Services on behalf of a company or other legal entity, you represent and warrant that you are authorized to bind such company or entity to this Agreement, in which case the terms “Customer,” “you,” and “your” will also refer to such company or entity. 

By (a) clicking “Agree” when registering a ProCliq account; (b) submitting your order via the ProCliq website, software, or app or an authorized third-party reseller (“Order”); or (c) using or accessing ProCliq products, you agree to be bound by this Agreement. If you do not agree to all of the terms of this Agreement, do not access or use the Services or Software.

1. Scope of Agreement.  This Agreement applies to both paid and freeware versions of ProCliq services available through the ProCliq website, app, or software (“Services”). By entering into this Agreement, you are also agreeing to our Privacy Policy, Acceptable Use Policy , Copyright Policy, Third-Party Product Terms, Service-Specific Terms, and any other referenced policies and attachments, which are incorporated by reference into this Agreement. This Agreement governs your use of all ProCliq services offered via the ProCliq website, app, or software, except for add-ons or plugins from third-party vendors available through the ProCliq website or app, which are covered under the terms of such third-party vendor. No terms of any ProCliq reseller (a “Reseller”) shall be binding on ProCliq except as specified in this Agreement. Such Resellers have no authority to make any promises or commitments on ProCliq’s behalf.  

2. Changes to this Agreement. ProCliq may update or modify this Agreement from time to time, including any referenced policies and other documents. If a revision materially reduces your rights, in ProCliq’s sole discretion, we will use reasonable efforts to notify you by sending an email to the designated email address in your account at such time or posting on our website, your account, or through the Service itself (“ProCliq Notice Methods”). You are responsible for checking these postings regularly. If we revise this Agreement during your Term, the revision will be effective upon your next renewal of a Term. Revisions to the Agreement shall be effective immediately with respect to free Services and Software.  If you object to the revised Agreement, as your exclusive remedy, you may choose not to renew or may cancel within 30 days of receiving the notice of change. Where applicable, we'll offer you a prorated portion of prepaid Services fees for the unused remainder of your subscription Term if you cancel within such 30-day window. 

3. Your Use of the Services.

3.1 Access and Use of Services. Subject to the payment in full of all fees and the terms and conditions of this Agreement, ProCliq grants you a limited, non-exclusive, non-transferable, non-sublicensable, revocable right to access and use the Services and the documentation provided with the Services and Software, as applicable (“Documentation”), in accordance with this Agreement, your applicable Scope of Use (defined below), and the Documentation, solely for use in the regular course of your business. Some of our Services allow you to download client software ("Software"). Subject to the terms and conditions of this Agreement, we also grant you a limited, non-exclusive, non-transferable, non-sublicensable, revocable license to install and use the Software, solely to access the Services in accordance with this Agreement, your applicable Scope of Use, and the Documentation and solely for use in the regular course of your business. The Software may require a license key in order to operate, which we will deliver as described in Section 4.7.  You are solely responsible for installing and maintaining, at your own expense, any and all internet connectivity, equipment, facilities and other services necessary for you and your Authorized Users (defined below) to access and use both paid and freeware versions of the Services and Software. 

3.2 Changes to Services/Software.  You acknowledge and agree that ProCliq may alter, modify, add, discontinue, automatically update, or otherwise change the Services, Software, and Documentation from time to time in its sole discretion and without notice. You acknowledge and agree that you are not relying on the future release of any added features or enhancements to the Services or Software or future availability of any Services or Software beyond the current Term. Any statements made by ProCliq regarding future product plans reflect ProCliq’s good-faith intent but do not constitute any guarantee of future availability and must not be relied on in deciding whether to purchase a Paid Account subscription or use freeware versions of the Services or Software.

3.2. Scope of Use. Your use of the Services and Software is limited to the features associated with the account level(s) and number of authorized users selected in your Order(s). Use of paid account Services is limited to the applicable subscription Term, as described in Section 4.1 below. A description of the features associated with different account levels can be found here (each, an “Account Level”). Your use of paid account Services is limited to the specific number of employees or contractors for which you have paid the required fees and whom you designate through the Procliq website or app (“Authorized Users”). Some Services may allow you to designate different types of Authorized Users, in which case pricing and functionality may vary according to the type of Authorized User.

3.3. Service-Specific Terms. Some ProCliq Services may be subject to additional terms as set forth here (“Service-Specific Terms”). To the extent you use such Services, those additional terms are incorporated into this Agreement. In the event of any conflict between this document and the Service-Specific Terms, the Service-Specific Terms shall control.  

3.4  Beta Services.  ProCliq may provide you access to products and features that it is still testing and evaluating. Those Services or Software have been marked beta, preview, early access, or evaluation (“Beta Services”). To the maximum extent permitted by applicable law, ProCliq disclaims all obligations or liabilities with respect to Beta Services, including any support, maintenance, warranty, and indemnity obligations. You agree that: (a) Beta Services may not be supported and may be terminated or changed at any time without notice; (b) Beta Services may not be as reliable, secure, or available as the Services; (c) Beta Services are not subject to the same security measures; and (d) PROCLIQ WILL HAVE NO LIABILITY ARISING OUT OF OR IN CONNECTION WITH BETA SERVICES.  ALL USE OF BETA SERVICES IS AT YOUR OWN RISK.

4. Paid Accounts
	
4.1. Subscription Terms and Renewals. You can increase your storage space and add paid features to your account (in such case, referred to as a "Paid Account"). Paid Account Services are provided on a monthly or yearly basis as selected in your Order (“Term”). All Paid Account Services must be prepaid in advance, and ProCliq will automatically bill you from the date you convert to a Paid Account and on each renewal until cancellation. Unless (a) you cancel or elect not to renew within your account settings on the ProCliq website, (b) you fail to timely pay prior to the beginning of a renewal Term, or (c) this Agreement is terminated pursuant to Section 12, all Paid Account subscriptions automatically renew for periods equal to your initial Term at the rates in effect at the time of your renewal. 

4.2. Payment. You agree to pay all fees specified at check-out for the Order and each renewal. Other than as expressly set forth in Sections 2, 4.6, 10.1, and 12.2, all amounts are non-refundable. You must maintain have a valid designated payment method at the end of your subscription Term for all Paid Accounts. You authorize ProCliq, or a third-party payment processor of ProCliq, to charge your designated payment method for the amount of the applicable then-current fees for all renewals, additional Authorized Users, and unpaid fees, as applicable, during the Term.  If you purchase any Services through a Reseller, you owe payment to the Reseller as agreed between you and the Reseller. Any amounts not paid when due shall accrue interest at the lesser of a rate of _____ percent per annum compounded daily or the maximum amount of interest permitted under applicable law. You shall reimburse ProCliq for all expenses incurred in the collection of amounts that are properly due under this Agreement, but are not paid within thirty days of their due date. Such reimbursable expenses shall include, without limitation, all associated legal costs.  The remedies provided for ProCliq in this Section 4.2 are cumulative and in addition to any other remedy available to ProCliq by law.

4.3. Taxes. All Fees and other amounts payable by you under this Agreement are exclusive of taxes and similar assessments. You are responsible for all sales, use, and excise taxes, and any other similar taxes, duties, and charges of any kind imposed by any federal, state, or local governmental or regulatory authority on any amounts payable by you hereunder (“taxes”), other than any taxes imposed on ProCliq’s income. If you provide ProCliq with a valid exemption certificate, ProCliq will not collect the taxes covered by that certificate. To the extent that any such taxes or duties are payable by ProCliq, you must pay ProCliq the amount of such taxes or duties in addition to any fees owed under this Agreement. 

4.4. Non-payment; Downgrades. If you cancel or don't pay for your Paid Account Order or renewal on time, ProCliq may suspend it and reduce your storage and other features to basic or free levels. You acknowledge and agree that a downgrade will result in a decrease in certain features and functionality and potential loss of access to Customer Data, as outlined in the account levels descriptions on the ProCliq site.

4.5 Rate Changes. ProCliq may from time to time change the Service or Software fees upon at least 30 days’ advance notice of these changes to the email address associated with your account. 

4.6. Refunds.  Refunds are only issued if required by law. If you live in a region where ProCliq is legally required to provide a refund for early cancellation, please submit your request here. For example, if you reside in the European Union, you may have the right to receive a refund if you cancel your Paid Account subscription(s) within 14 days of signing up for, upgrading to or renewing a Paid Account.

4.7.  Delivery. ProCliq will deliver the applicable license keys for applicable Software or login instructions for Paid Account Services to the email address specified in your account or Order after it has received full payment of all applicable fees. All deliveries under this Agreement will be electronic. 

5. Restrictions and Limitations.  You and your Authorized Users must use the Services and Software in compliance with our Acceptable Use Policy, this Agreement, and the Documentation. Except as otherwise expressly permitted in this Agreement, you will not and will not assist others to: (a) rent, lease, reproduce, modify, adapt, create derivative works of, distribute, sell, sublicense, transfer, or provide access to the Services, Documentation, or Software to a third party; (b) use the Services, Documentation, or Software for the benefit of any third party; (c) incorporate any Services, Software, or Documentation into a product or service you provide to a third party; (d) develop any third-party applications or services that interact with the Services or Software without ProCliq’s prior written consent; (e) interfere with or otherwise circumvent mechanisms in the Services or Software intended to limit access or use or attempt to gain unauthorized access to the Services, Software, or related systems or networks; (f) interfere with or disrupt the integrity or performance of the Services, Software, or any parties’ data contained therein; (g) reverse engineer, disassemble, decompile, translate, or otherwise seek or attempt to discover the source code to any Services or Software, except to the extent permitted by applicable law, if applicable to you; (h) use Services, including Beta Services, or Software for competitive analysis or in order to build a competitive product or service; (i) use Services or Software for any illegal or unauthorized purpose or engage in, encourage, or promote any activities that violate the terms or conditions of this Agreement; (j) engage in any unlawful, harassing, intimidating, predatory or objectionable conduct using the Services or Software; (k) infringe or violate any intellectual property, privacy, publicity, or other proprietary or personal rights of any third party; (l) knowingly distribute via, upload to, or store within Services any virus, trojan horse, corrupted data, or other harmful, malicious, disruptive or destructive files or content; (m) remove or obscure any proprietary or other notices contained in any Service or Software; (n) use any data mining, robots or similar data gathering or extraction methods; (o) use the Services or Software for activities that could result in any harm or injury to ProCliq or any third party; (p) use the Services or Software, including the export or re-export of Customer Data, in violation of Export Control Laws (defined below); or (q) take any action that results in the Services or Software being subject to a license that requires, or purports to require, as a condition of use, modification, or distribution, that (i) the code that is or could become subject to the license, be disclosed or distributed in source code form, or (ii) others have the right to modify or create derivative works of the code that is or could become subject to the license.  

6. Accounts; Authorized Users; Suspension.

6.1. Account Registration. You need to register for a ProCliq account to place Orders or access or use any of the Services. You agree to keep all account information current and accurate during this Agreement.  ProCliq may send notices, statements and other information to you by email or through your account. 

6.2. Customer Responsibility for Accounts.  You are responsible and liable for all uses of the Services, Software, and Documentation resulting from access provided through your account(s), directly or indirectly. You must immediately notify ProCliq in writing if you become aware of any unauthorized use of any account or any other breach of security related to the ProCliq Services or Software. In the event any unauthorized third party obtains access to the Services directly or indirectly through you or any of your Authorized User accounts, you shall immediately take all steps necessary to terminate such unauthorized use and cooperate and assist as reasonably requested by ProCliq. 

6.3. Age Requirements. No one under 18 years old may register for an account or use any of the Services or Software without a duly signed parent/guardian authorization form, in form and substance acceptable to ProCliq. You can request an authorization form here.  Under no circumstances may anyone under 13 years old register for an account or use any of the Services or Software or otherwise use the ProCliq website, and you agree not to allow any person under 13 to use the Services or Software. You must promptly notify ProCliq of any unauthorized use of or access to the Services or Software.

6.4. Authorized Users.  You may allow up to the number of Authorized Users to access your Paid Account Services as permitted under the Scope of Use associate with your account level. All use of Services by you and your Authorized Users must be within the Scope of Use and solely for the benefit of you or your corporate affiliates. You are responsible for (a) ensuring compliance with this Agreement by all Authorized Users; (b) all actions taken via your account(s) or your Authorized User’s account(s); and (c) the security of all user credentials associated with your account(s) and your Authorized User’s account(s). Without limiting the foregoing, any and all acts or omissions by Authorized User, which would constitute a breach of this Agreement if taken by you, shall constitute a breach of this Agreement by you. You must advise all Authorized Users of the terms of this Agreement and shall ensure their compliance with its terms. 

6.5. Team Accounts. Certain Services may require you to register a Team Account or join a Team Account.  If you join a Team Account, you must use it in compliance with the Team Account Scope of Use and the Team Account organization's terms and policies. Please note that Team Accounts are subject to the Team Account organization’s control. Team Account administrators may be able to access, disclose, restrict, or remove information in or from your Team Account. They may also be able to restrict or terminate your access to a Team Account. 

7.  ProCliq IP. 

7.1. ProCliq IP. You acknowledge and agree that, as between you and ProCliq, ProCliq and its licensors, as applicable, own all right, title, and interest, including all intellectual property rights, in and to the Services and Software (including all Beta Services and Software), including the ProCliq website, their “look and feel”, any and all related or underlying technology, and any modifications or derivative works of the foregoing created by or for ProCliq, including without limitation as they may incorporate Feedback (“ProCliq IP”). Services and Software are made available on a limited license or access basis, and no ownership right is conveyed to you, notwithstanding any use of terms such as “purchase” or “sale”. ProCliq reserves all rights not expressly granted to you in this Agreement. Except for the limited rights and licenses expressly granted under this Agreement, nothing in this Agreement grants, by implication, waiver, estoppel, or otherwise, to you or any third party any intellectual property rights or other right, title, or interest in or to the ProCliq IP. 

7.2. Feedback.  If you, any Authorized Users, or other employees, contractors, or representatives  send or transmit any communications or materials to ProCliq by mail, email, telephone, through the Services, or otherwise, suggesting or recommending changes to the Services, Software, Documentation, or other ProCliq IP, including without limitation, new features or functionality, or any comments, questions, suggestions, or the like (“Feedback”), ProCliq is free to use such Feedback irrespective of any other obligation or limitation between the parties governing such Feedback. ProCliq shall own all rights in and to Feedback, including all intellectual property and other proprietary rights, and will be entitled to freely make, use, copy, modify, create derivative works of, incorporate, disclose, license, sublicense (through multiple tiers), sell, distribute, import, export, and otherwise exploit any Feedback in any manner without any obligation, royalty or restriction based on intellectual property rights or otherwise. No Feedback will be considered your confidential information, and nothing in this Agreement limits ProCliq's right to independently use, develop, evaluate, or market products, whether incorporating Feedback or otherwise.

8. Customer Data.

8.1. “Customer Data” means any content, data, images, video, or other materials of any type that you upload, submit, or otherwise transmit to or through the Services. You will retain all right, title, and interest in and to Customer Data in the form provided to ProCliq. Subject to the terms of this Agreement, you hereby grant to ProCliq a limited, non-exclusive, worldwide, royalty-free, sublicensable (through multiple tiers) right to collect, access, use, copy, store, transmit, process, perform, import, export, modify, and adapt Customer Data, solely to the extent necessary to (a) provide, maintain, and improve the Services, as reasonably necessary; (b) to prevent or address service, security, support, or technical issues; (c) as required by law or as permitted by our Privacy Policy; and (d) as you expressly permit in writing. You represent and warrant that you have obtained and will maintain throughout the term of this Agreement all rights in and to Customer Data necessary to grant this license.  

8.2. Security. ProCliq maintains reasonable security measures in its systems and networks to protect Customer Data from unauthorized access by third parties. ProCliq will not be responsible for any unauthorized access to any Customer Data that (a) results from the use or misuse of your account or any Authorized User accounts; (b) results from any breach of your privacy or data protection policies or procedures by you, your Authorized Users, or any third party; (c) occurs through your systems or networks; or (d) results from any vulnerabilities or weaknesses in your or your Authorized User’s devices, equipment, facilities, networks or systems. Further, you understand that (i) use of the Services necessarily involves transmission of Customer Data over networks that are not owned, operated or controlled by ProCliq; (ii) ProCliq is not responsible for any of Customer Data lost, altered, intercepted or stored across such networks; and (iii) ProCliq cannot guarantee that its security measures will be error-free, that transmissions of Customer Data will always be secure, or that unauthorized third parties will never be able to defeat our security measures or those of our third-party providers.

8.3. Storage Limits. Storage limits vary based on account level. Descriptions can be found here. ProCliq may impose new or may modify existing storage limits for the Services and account levels at any time in its discretion as described in Section 2.  ProCliq may charge for additional storage or overage fees at the rates specified here. 

8.4. Your Requirements Regarding Customer Data. ProCliq is not responsible for the content of any Customer Data. ProCliq may, but has no obligation to, monitor any content uploaded to the Services. You must ensure that your use of all Services, Software, and all Customer Data is at all times compliant with ProCliq’s Acceptable Use Policy and all applicable local, state, federal and international laws and regulations (“Laws”). You must not create, upload, post or store any Customer Data that (a) may create any liability, violate any Laws, or result in any harm or injury to ProCliq or any third party; (b) involves the publication of any material or content that is false, defamatory, untruthful, unlawful, harassing or obscene; (c) violates or infringes any intellectual property, privacy, publicity, or other proprietary or personal rights of any third party; or (d) contains any virus, trojan horse, corrupted data, or other harmful, malicious, disruptive, or destructive files or content. In addition to the other rights afforded to ProCliq under this Agreement, ProCliq reserves the right, but has no obligation, to remove and take other reasonable remedial action regarding any such Customer Data, without any liability to you or any of your Authorized Users. Other than its security obligations under Section 7.2 (Security), ProCliq assumes no responsibility or liability for Customer Data, and you shall be solely responsible for Customer Data and the consequences of using, disclosing, storing, or transmitting it. Nonetheless, if ProCliq deems such action necessary based on your violation of this Agreement or in response to takedown requests that we receive following ProCliq’s Copyright Policy, ProCliq may immediately (1) remove Customer Data from the Hosted Services or (2) suspend your access to the Services. ProCliq will typically alert you prior to taking such action and give you a reasonable opportunity to cure your breach, but if ProCliq determines, in its sole discretion, that your actions endanger the operation of the Service or other users or their data or use of the Services or Software, ProCliq may suspend your access immediately without notice. We have no liability to you for removing or deleting Customer Data from or suspending your access to any Services as described in this section.

8.5. Public Postings.  If you or any of your Authorized Users use, upload, or post any Customer Data to the publicly accessible areas of the Services, you and your Authorized Users expressly acknowledge that such Customer Data may be viewable by the public or other ProCliq customers, as applicable. You are solely responsible for any uploading or posting of Customer Data in any publicly-accessible areas of the Services by you or any of your Authorized Users.

8.6. Backups; Deletion at End of Term. You bear sole responsibility for adequate backup of all Customer Data at all times. ProCliq will not be responsible for any corruption, deletion, destruction or loss of any Customer Data. ProCliq may remove or delete Customer Data to the applicable downgraded storage level after the expiration of the applicable Term in the event of your election not to renew or failure to timely make a renewal payment. 

9.  Aggregated Data.  Notwithstanding anything to the contrary in this Agreement, ProCliq may monitor your use of the Services and Software and collect and compile data and information related to your use of the Services that is used by ProCliq in an aggregate and anonymized manner, including to compile statistical and performance information related to the provision and operation of the Services (“Aggregated Statistics”). As between you and ProCliq, all right, title, and interest in Aggregated Statistics, and all intellectual property rights therein, belong to and are retained solely by ProCliq. You acknowledge that ProCliq may compile Aggregated Statistics based on Customer Data input into the Services. You agree that ProCliq may (i) make Aggregated Statistics publicly available in compliance with applicable law, and (ii) use Aggregated Statistics to the extent and in the manner permitted under applicable law. 

10.  Subcontractors; Independent Contractors.  You acknowledge and agree that ProCliq may engage third parties to assist in performance of the Services, provided, however, that use of such subcontractors shall not relieve ProCliq of any of its obligations under this Agreement.

11. Warranty and Disclaimer.

11.1. Warranties. Each party represents and warrants that (a) it has the full right, power and authority to enter into this Agreement, to grant the rights and licenses granted under this Agreement and to perform its obligations under this Agreement; and (b) it does not have any contractual or other arrangements that will interfere with rights herein granted.  You represent and warrant that, once accepted by you in accordnace with one of the methods described in the second introductory paragraph above, this Agreement will constitute your legal, valid, and binding obligation, enforceable in accordance with its terms, subject to bankruptcy, insolvency, moratorium, reorganization, or similar laws affecting the rights of creditors generally and the availability of equitable remedies.

11.2 WARRANTY DISCLAIMER. EXCEPT AS EXPRESSLY SET FORTH IN THIS AGREEMENT, ALL SERVICES ARE PROVIDED “AS IS,” AND PROCLIQ DOES NOT MAKE ANY EXPRESS OR IMPLIED WARRANTIES, CONDITIONS, OR REPRESENTATIONS TO YOU OR ANY OTHER PARTY WITH RESPECT TO THE SERVICES, SOFTWARE, DOCUMENTATION, OR OTHERWISE RELATING TO THIS AGREEMENT, WHETHER ORAL OR WRITTEN, EXPRESS, IMPLIED, OR STATUTORY. WITHOUT LIMITING THE FOREGOING, ANY IMPLIED WARRANTIES OF MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE, TITLE, AND NON-INFRINGEMENT ARE EXPRESSLY EXCLUDED AND DISCLAIMED. PROCLIQ DOES NOT WARRANT, GUARANTEE, OR MAKE ANY REPRESENTATIONS REGARDING THE USE OF, OR THE RESULTS OF THE USE OF, THE SERVICES, SOFTWARE, DOCUMENTATION, OR OTHERWISE RELATING TO THIS AGREEMENT IN TERMS OF CORRECTNESS, ACCURACY, RELIABILITY, OR OTHERWISE AND DOES NOT WARRANT THAT (A) THE OPERATION OF THE SERVICES OR SOFTWARE WILL BE SECURE, TIMELY, UNINTERRUPTED, OR ERROR FREE; (B) THE SERVICES OR SOFTWARE WILL OPERATE IN COMBINATION WITH ANY OTHER HARDWARE, SOFTWARE, SYSTEM, OR DATA; (C) THE SERVICES OR SOFTWARE (OR ANY SERVICES, INFORMATION, OR OTHER MATERIAL PURCHASED OR OBTAINED BY YOU THROUGH THE SERVICES OR SOFTWARE) WILL MEET YOUR REQUIREMENTS OR EXPECTATIONS); OR (D) THE SERVICES, SOFTWARE, OR ANY SERVER(S) THAT MAKE A SERVICE AVAILABLE ARE FREE OF VIRUSES OR OTHER HARMFUL COMPONENTS. WITHOUT LIMITING THE GENERALITY OF THE FOREGOING, PROCLIQ SHALL NOT BE LIABLE FOR DELAYS, INTERRUPTIONS, SERVICE FAILURES AND OTHER PROBLEMS INHERENT IN USE OF THE INTERNET AND ELECTRONIC COMMUNICATIONS OR OTHER SYSTEMS OUTSIDE THE REASONABLE CONTROL OF PROCLIQ. WHERE YOU HAVE OTHER STATUTORY RIGHTS, THE DURATION OF ANY STATUTORILY REQUIRED WARRANTIES APPLICABLE TO YOU OR YOUR AUTHORZIED USERS, SHALL BE LIMITED TO THE SHORTEST PERIOD AND TO THE MINIMUM SCOPE PERMITTED BY APPLICABLE LAW. 

12. Indemnification

12.1. Indemnification by ProCliq.  ProCliq will indemnify, defend and hold you harmless from and against any claim by a third party alleging that the Services, Software, or Documentation (excluding any third-party intellectual property or Customer Data included therein) infringe any intellectual property rights that are protectable under US law. Notwithstanding the foregoing, ProCliq shall have no obligations for any claim described above if the claim arises from: (i) a combination of the Services or Software with components or materials not provided by ProCliq; (ii) any modifications or additions to the Services or Software not made directly by ProCliq; (iii) the use of Customer Data; or (iv) the negligence, intentional misconduct, unlawful act, or other breach of this Agreement by you or your Authorized Users (the “Excluded Claims”).  In the event that ProCliq reasonably believes that any of the Services or Software is, will, or may be alleged to infringe a third party’s intellectual property rights, ProCliq may: (a) secure for you the right to use the Services or Software; (b) provide a substitute with substantially similar functionality; or (c) return a prorated portion of any prepaid fees paid for the Services or Software for the unused remainder of your subscription Term, in which case you and your Authorized Users shall cease using the affected Services or Software, and any intellectual property rights in the affected Services or Software.  THIS SECTION 10.1 SETS FORTH YOUR AND YOUR AUTHORIZED USERS’ SOLE REMEDIES AND PROCLIQ’S SOLE LIABILITY AND OBLIGATION FOR ANY ACTUAL, THREATENED, OR ALLEGED CLAIMS THAT THE SERVICES, SOFTWARE, OR DOCUMENTATION INFRINGE, MISAPPROPRIATE, OR OTHERWISE VIOLATE ANY INTELLECTUAL PROPERTY RIGHTS OF ANY THIRD PARTY.

12.2. Customer Indemnity.  You will indemnify, defend, and hold ProCliq, its affiliates, and their representatives, officers, directors, employees, agents, successors and assigns harmless from and against: (i) any claim by any third party that Customer Data infringes any third party’s intellectual property, privacy, publicity, or other proprietary or personal rights; and (ii) any Excluded Claim.

12.3. Procedure.  A party’s sole obligation for a claim subject to indemnity pursuant to Sections 10.1 or 10.2 (each an “Indemnified Claim”) shall be to (i) defend the Indemnified Claim by providing and paying for counsel reasonably acceptable to the indemnified party, and (ii) pay any final judgment resulting from the Indemnified Claim or any settlement entered into in accordance with this Section 10.3. The indemnified party shall (a) notify the indemnifying party in writing promptly after the indemnified party becomes aware of a Indemnified Claim or the possibility thereof; (b) grant the indemnifying party sole control of the settlement, compromise, negotiation, and defense of the Indemnified Claim; provided however, that no settlement that affects the rights or interest of the indemnified party may be settled without such party’s consent, and provided further that the indemnified party may participate in the defense with its own counsel and at its own expense; and (c) provide the indemnifying party with all information related to the Indemnified Claim that is reasonably requested by the indemnifying party.

13. Limitation of Liability. IN NO EVENT WILL EITHER PARTY BE LIABLE TO THE OTHER PARTY, ITS SUBCONTRACTORS, CUSTOMERS, AFFILIATES, REPRESENTATIVES, OR AGENTS (“RELATED PARTIES”) FOR ANY (A) INDIRECT, CONSEQUENTIAL, INCIDENTAL, SPECIAL, PUNITIVE, OR LOST PROFITS DAMAGES EVEN IF ADVISED OF THE POSSIBILITY THEREOF, INCLUDING (WITHOUT LIMITATION) LOSS OF PROFIT, INCOME, SAVINGS, CLAIMS OF YOUR CUSTOMERS, DIMINUTION IN VALUE, LOSS OF GOODWILL OR REPUTATION, USE; (B) INABILITY TO USE, LOSS, INTERRUPTION, DELAY OR RECOVERY OF ANY DATA; OR (C) BREACH OF DATA OR SYSTEM SECURITY. TO THE MAXIMUM EFFECT UNDER APPLICABLE LAW, IN NO EVENT WILL EITHER PARTY’S LIABILITY FOR CLAIMS, OBLIGATIONS, AND LOSSES ARISING OUT OF OR RELATED TO THE SERVICES, SOFTWARE, DOCUMENTATION, OR OTHERWISE RELATED TO THIS AGREEMENT, UNDER ANY THEORY OF LAW (INCLUDING ANY CLAIMS FOR BREACH, STRICT LIABILITY, SPECIFIC PERFORMANCE, INDEMNITY, OR TORT, INCLUDING NEGLIGENCE) EXCEED IN THE AGGREGATE THE SUM OF FEES PAID AND OWED BY YOU UNDER THE ORDER GIVING RISE TO THE CLAIM WITHIN THE 12-MONTH PERIOD PRECEDING THE EVENTS GIVING RISE TO SUCH CLAIM. THIS SECTION 11 SHALL NOT APPLY TO (1) PROCLIQ’S ABILITY TO RECOVER FEES OWED UNDER THIS AGREEMENT AS PROVIDED HEREIN; OR (2) YOUR BREACH OF SECTION 5. The parties acknowledge and agree that the fees for the Services and Software reflect this allocation of risk, and these limitations of liability shall apply even if any limited remedy specified in this Agreement is found to have failed of its essential purpose.

14. Suspension. Notwithstanding anything to the contrary in this Agreement, ProCliq may suspend your and any Authorized Users access to any portion or all of the Services if ProCliq reasonably determines that (a) there is a threat or attack on any of the Services or other ProCliq IP; (b) you or any Authorized User’s use of the Services or other ProCliq IP disrupts or poses a security risk to the ProCliq IP or to any other customer or vendor of ProCliq; (c) you or any Authorized User is using the Services or other ProCliq IP for fraudulent or illegal activities or otherwise in violation of this Agreement, including the Acceptable Use Policy; (d) you or your Authorized Users use the Services or Software in a manner that ProCliq reasonably believes will cause it liability; (e) ProCliq’s provision of the Services to you or any Authorized User is prohibited by applicable law; or (f) if you are subject to an Insolvency Event (defined below). Further, ProCliq may immediately suspend use of the Services or Software in the event of (i) unauthorized third-party access to the Services or Software; (ii) use of the Services or Software that could disrupt the Services or the infrastructure used to provide the Services; (iii) any vendor of ProCliq has suspended or terminated ProCliq’s access to or use of any third-party services or products required to enable you or any Authorized User to access the Services; or (iv) as otherwise provided in this Agreement. ProCliq shall use commercially reasonable efforts to provide you notice of any Service suspension. ProCliq will have no liability for any damage, liabilities, losses, including any loss of data or profits, or any other consequences that you or any Authorized User may incur as a result of a Service suspension.  

15. Termination. 

15.1 Termination. This Agreement is in effect for as long as you have a valid account, unless sooner terminated as permitted in this Agreement. Either party may terminate this Agreement if the other party materially breaches this Agreement and fails to cure that breach within 30 days of receiving written notice specifying the breach in reasonable detail. This 30-day cure period shall not apply to a party’s immediate termination rights specified in this Agreement. You may terminate this Agreement at any time with notice to ProCliq, but you will not be entitled to any credits or refunds as a result of convenience termination for prepaid but unused subscriptions. To the extent permitted by applicable law, if a party: (i) files for bankruptcy; (ii) becomes or is declared insolvent, or is the subject of any involuntary proceedings related to its liquidation, insolvency or the appointment of a receiver or similar officer for it that are not dismissed within 90 days after they are commenced; or (iii) makes an assignment for the benefit of all or substantially all of its creditors (an “Insolvency Event”), then the other party may terminate this Agreement by giving written notice of termination to that party, effective as of the date specified in that notice of termination. 

15.2. Effect of Termination. Upon termination of this Agreement, (a) all licenses granted by ProCliq under this Agreement shall immediately cease, and (b) ProCliq may delete any of your or your Authorized Users’ Customer Data. You are required to delete all ProCliq IP from your systems and, upon request, certify to us in writing that you have done so. If you terminate this Agreement for cause, ProCliq will refund you a prorated portion of prepaid Services fees for the unused remainder of your subscription Term. The following provisions will survive any termination or expiration of this Agreement for any reason: Sections 1, 3.3, 3.4, 4.2-4.6, 5, 6.2-6.5, 7, 8.2(i)-(iii), 8.4-8.6, 9, 10, 11.2, 13-17, and 19-21.
.

16. Excused Performance. If a party is prevented from performing or is unable to perform any of its obligations under this Agreement (other than your payment obligations) due to causes beyond the reasonable control of that party, including any internet service provider failure or delay or act of God, fire, casualty, flood, war, terrorism, strike, lockout, riot, or insurrection, then its performance will be excused, and the time for the performance will be extended, for the period of delay or inability to perform due to such occurrences.

17. Third-Party Products.  ProCliq may from time to time make third-party products or services, including but not limited to add-ons and plugins (“Third-Party Products”) available to you or your Authorized Users. For purposes of this Agreement, such Third-Party Products are subject to their own terms and conditions and the applicable flow-through provisions referred to in the applicable Third-Party Product Terms. If you or your Authorized Users do not agree to abide by the applicable terms for any such Third-Party Products, then Customer should not install or use such Third-Party Products. ProCliq does not warrant or support Third-Party Products, whether or not they are designated by ProCliq as “verified” or otherwise, and disclaims all liability for such products or services. If you install or enable any Third-Party Products, you acknowledge that ProCliq may allow the vendors of those products and services to access Customer Data as required for the interoperation and support of such add-ons with the ProCliq products. ProCliq shall not be responsible for any disclosure, modification or deletion of Customer Data resulting from any such access by Third-Party Product providers. 

18. Publicity Rights.  You agree that we may identify you as a ProCliq customer in our promotional materials. You may request that we stop doing so by submitting an email to us at any time. Please note that it may take us up to 30 days to process your request.  

19.  Copyright Policy. ProCliq respects the intellectual property of others and asks that you do the same. ProCliq responds to notices of alleged copyright infringement reported using our Copyright Policy. We reserve the right to delete or disable content alleged to be infringing and terminate accounts of repeat infringers. Our designated agent for notice of alleged copyright infringement on the Services is:

[INSERT COPYRIGHT AGENT CONTACT INFO.]

20. Export Restrictions. The Services and Software utilize technology that may be subject to US export control laws, including the US Export Administration Act and its associated regulations (“Export Laws”). You and your Authorized Users shall not, directly or indirectly, export, re-export, or release the Services, Software, or the underlying software or technology to, or make the Services, Software, or the underlying software or technology accessible from, any jurisdiction or country to which export, re-export, or release is prohibited by law, rule, or regulation. You and your Authorized Users must comply with all applicable federal laws, regulations, and rules, and complete all required undertakings (including obtaining any necessary export license or other governmental approval), prior to exporting, re-exporting, releasing, or otherwise making the Services, Software, or the underlying software or technology available outside the US.

21. General.

21.1. Remedies; Injunctive Relief. Except where an exclusive remedy may be specified in this Agreement, the exercise by either party of any remedy, including termination, will be without prejudice to any other remedies it may have under this Agreement, by law, or otherwise. You acknowledge and agree that a breach or threatened breach by you or your Authorized Users of any of the obligations under Sections 5, would cause ProCliq irreparable harm for which monetary damages would not be an adequate remedy and agrees that, in the event of such breach or threatened breach, ProCliq will be entitled to equitable relief, including a restraining order, an injunction, specific performance and any other relief that may be available from any court, without any requirement to post a bond or other security, or to prove actual damages or that monetary damages are not an adequate remedy. Such remedies are not exclusive and are in addition to all other remedies that may be available at law, in equity or otherwise. 

21.2. Notices.  Any notice under this Agreement must be given in writing. We may provide notice to you via any of the ProCliq Notice Methods. ProCliq’s notices to you will be deemed given upon the first business day after we send it. You may provide notice to us by mail to ProductionCliq, LLC, ________________________, Attn: ___________. 

21.3. Relationship of Parties.  Each party is an independent entity and neither party has the authority to bind, represent, or commit the other to any obligation to a third party except as expressly set forth in this Agreement. Nothing in this Agreement is intended to create an employment or co-employment relationship, a joint venture, a partnership, franchise, or any agency relationship between the parties.

21.4. Assignment.  Neither party may assign this Agreement without the prior written consent of the other party, except that either party may assign this Agreement in connection with a merger, reorganization, or sale to an entity that purchases all or substantially all of that party’s assets and agrees to assume all of the party’s obligations under this Agreement.  ProCliq will not unreasonably withhold our consent if the assignee agrees to be bound by the terms and conditions of this Agreement. This Agreement will be binding upon and inure to the benefit of the parties and their respective successors, representatives (including executors, administrators, and legal guardians), heirs, and permitted assigns.

21.5. Waiver. No failure or delay by the injured party to this Agreement in exercising any right, power or privilege hereunder shall operate as a waiver thereof, nor shall any single or partial exercise thereof preclude any other or further exercise thereof or the exercise of any right, power or privilege hereunder at law or equity.

21.6. US Government Rights. Each of the Services (and underlying software and other technology), Software, and Documentation is a “commercial item” as that term is defined at 48 C.F.R. § 2.101, consisting of “commercial computer software” and “commercial computer software documentation” as such terms are used in 48 C.F.R. § 12.212. Accordingly, if you are an agency of the US Government or any contractor therefor, you only receives those rights with respect to the Services, Software, and Documentation as are granted to all other end users, in accordance with (a) 48 C.F.R. § 227.7201 through 48 C.F.R. § 227.7204, with respect to the Department of Defense and their contractors, or (b) 48 C.F.R. § 12.212, with respect to all other US Government users and their contractors.

21.7.	Invalidity.  If any provision of this Agreement is determined to be illegal or unenforceable, then the provision will be deemed to be restated to reflect as nearly as possible the original intentions of the parties in a manner that complies with applicable law.  The remainder of this Agreement, if capable of substantial performance, will remain in full force and effect.

21.8. Governing Law; Venue.  This Agreement, and all claims arising out of or relating to its subject matter, shall be exclusively governed by and construed under the internal laws of the State of Texas, without regard to its conflicts of laws rules.  Any action, suit, or other legal proceeding that is commenced to resolve any matter arising under or relating to this Agreement or the Services shall be commenced only in the state and federal courts located in Travis County, Texas.

21.9. Exclusion of UN Convention and UCITA. The terms of the United Nations Convention on Contracts for the Sale of Goods do not apply to this Agreement. The Uniform Computer Information Transactions Act (UCITA) shall not apply to this Agreement regardless of when or where adopted.

21.10. WAIVER OF JURY TRIAL. TO THE EXTENT NOT PROHIBITED BY APPLICABLE LAW, EACH PARTY HEREBY KNOWINGLY, VOLUNTARILY, INTENTIONALLY, AND IRREVOCABLY WAIVES ANY RIGHT TO A JURY TRIAL FOR ANY DISPUTE RELATED TO OR ARISING FROM THIS AGREEMENT.

21.11. Limitations Period and Notice. You, your Authorized Users, and ProCliq agree that any action in relation to an alleged breach of this Agreement shall be commenced within two (2) years of the date of the breach. For ProCliq to be liable for breach of the Agreement, you must, as a condition precedent, give ProCliq written notice, no later than ninety-five (95) days after such breach, of such alleged breach that states, in reasonable detail, the facts constituting the alleged breach.

21.12. Complete Agreement.  This Agreement, which includes all documents expressly referenced in this Agreement, constitutes the entire agreement between the parties with regard to the subject matter of this Agreement, and supersedes all prior agreements, representations, proposals, discussions, and communications, whether oral or in writing, in relation to the subject matter of this Agreement. 

21.13. Construction. The headings of the articles and sections contained in this Agreement are for convenience only and shall not be deemed to control or affect the meaning or construction of any provision of this Agreement. Unless the context clearly requires otherwise, the words “shall”, “will”, “must”, and “agrees” are mandatory, “may” is permissive, “or” is not exclusive, and “includes” and “including” are not limiting. Whenever the context requires, references in this Agreement to the singular number shall include the plural, and the plural number shall include the singular. Words denoting gender shall include the masculine, feminine and neutral.  In the interpretation of this Agreement or any part of it, no rule of construction shall apply to the disadvantage of any party on the basis that such party prepared this Agreement or any part of it, but instead the Agreement is to be interpreted in accordance with the most reasonable construction. 


`;
