// flow-typed signature: c5ef98773947966f762bd8e8a0fd5a29
// flow-typed version: <<STUB>>/@firebase/app-types_v0.x/flow_v0.77.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   '@firebase/app-types'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module '@firebase/app-types' {
  declare module.exports: any;
}
